Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2019-09, with the labels that each got.

#1260 Update Get-SmbShare.md
  docset/winserver2012r2-ps/smbshare/Get-SmbShare.md
Labels: In review, SignOff

#1261 Update Unblock-SmbShareAccess.md
  docset/winserver2012r2-ps/smbshare/Unblock-SmbShareAccess.md
Labels: In review, SignOff

#1302 Updating LacpTimer to match Set cmdlet.
  docset/windows/netlbfo/new-netlbfoteam.md
Labels: In review

#1222 Added deprecated info
  docset/windows/hnvdiagnostics/disable-muxechoresponder.md
  docset/windows/hnvdiagnostics/enable-muxechoresponder.md
Labels: In review

#1162 Changed wording
  docset/windows/defender/defender.md
Labels: In review, SignOff

#1284 Update set-vpnserverconfiguration.md
  docset/windows/remoteaccess/set-vpnserverconfiguration.md
Labels: Ready to Merge

#1287 Update Add-VpnConnectionTriggerApplication.md
  docset/winserver2012r2-ps/vpnclient/Add-VpnConnectionTriggerApplication.md
Labels: SignOff

#1288 Update Add-VpnConnectionTriggerTrustedNetwork.md
  docset/winserver2012r2-ps/vpnclient/Add-VpnConnectionTriggerTrustedNetwork.md
Labels: Ready to Merge

#1292 Update OS codename reference to OS's release name
  docset/winserver2012r2-ps/netadapter/Enable-NetAdapterRss.md
Labels: In review, SignOff

#1293 Replace all firstref instances with OS names
  docset/windows/netadapter/set-netadapterrss.md
Labels: In review, SignOff

#1295 Add description for LacpTimer parameter
  docset/windows/netlbfo/set-netlbfoteam.md
Labels: In review, SignOff

#1298 NVGRE and VXLAN EncapsulatedPacketTaskOffloadEnabled parameters descr…
  docset/windows/netadapter/set-netadapterencapsulatedpackettaskoffload.md
Labels: In review, SignOff

#1311 Adding link with rule level description
  docset/windows/configci/new-cipolicy.md
Labels: In review, SignOff

#1300 Add EncapsulationType parameter description.
  docset/windows/netadapter/disable-netadapterencapsulatedpackettaskoffload.md
Labels: In review, SignOff

#1312 new-cipolicyrule: add link with level descriptions
  docset/windows/configci/new-cipolicyrule.md
Labels: In review, SignOff

#1286 Update get-ipamipaddressauditevent.md
  docset/windows/ipamserver/get-ipamipaddressauditevent.md
  docset/winserver2012r2-ps/ipamserver/Get-IpamIpAddressAuditEvent.md
Labels: In review

#1309 Update suspend-printjob.md
  docset/windows/printmanagement/suspend-printjob.md
  docset/winserver2012-ps/printmanagement/Suspend-PrintJob.md
  docset/winserver2012r2-ps/printmanagement/Suspend-PrintJob.md
Labels: In review

#1343 Update Unblock-SmbShareAccess.md
  docset/winserver2012-ps/smbshare/Unblock-SmbShareAccess.md
Labels: In review

#1316 Update Get-SmbWitnessClient.md
  docset/winserver2012r2-ps/smbwitness/Get-SmbWitnessClient.md
Labels: In review

#1319 Update PowerShellWebAccess.md
  docset/winserver2012r2-ps/powershellwebaccess/PowerShellWebAccess.md
Labels: In review

#1320 Update PEF.md
  docset/winserver2012r2-ps/pef/PEF.md
Labels: In review

#1328 Add parameter description in 2012 version
  docset/windows/addsadministration/get-addomaincontrollerpasswordreplicationpolicy.md
  docset/winserver2012-ps/activedirectory/Get-ADDomainControllerPasswordReplicationPolicy.md
  docset/winserver2012r2-ps/addsadministration/Get-ADDomainControllerPasswordReplicationPolicy.md
Labels: In review

#1338 Add -Node parameter description Get-S2D
  docset/windows/failoverclusters/get-clusterstoragespacesdirect.md
Labels: In review

#1356 Update Get-SmbSession.md
  docset/winserver2012-ps/smbshare/Get-SmbSession.md
  docset/winserver2012r2-ps/smbshare/Get-SmbSession.md
Labels: In review

#1363 Update Get-SmbOpenFile.md
  docset/winserver2012-ps/smbshare/Get-SmbOpenFile.md
  docset/winserver2012r2-ps/smbshare/Get-SmbOpenFile.md
Labels: In review

#1374 Add parameter description
  docset/windows/failoverclusters/get-clustervmmonitoreditem.md
  docset/winserver2012r2-ps/failoverclusters/Get-ClusterVMMonitoredItem.md
Labels: In review
