Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2019-10, with the labels that each got.

#1373 Add Parameter description in 2016 version
  docset/windows/failoverclusters/remove-clustervmmonitoreditem.md
  docset/winserver2012r2-ps/failoverclusters/Remove-ClusterVMMonitoredItem.md
Labels: In review

#1375 Add parameter description.
  docset/windows/failoverclusters/add-clustervmmonitoreditem.md
  docset/winserver2012-ps/failoverclusters/Add-ClusterVMMonitoredItem.md
  docset/winserver2012r2-ps/failoverclusters/Add-ClusterVMMonitoredItem.md
Labels: In review

#1350 Update Remove-SmbShare.md
  docset/winserver2012-ps/smbshare/Remove-SmbShare.md
  docset/winserver2012r2-ps/smbshare/Remove-SmbShare.md
Labels: In review

#1349 Update Revoke-SmbShareAccess.md
  docset/winserver2012-ps/smbshare/Revoke-SmbShareAccess.md
  docset/winserver2012r2-ps/smbshare/Revoke-SmbShareAccess.md
Labels: In review

#1401 Update Set-SmbShare.md
  docset/winserver2012-ps/smbshare/Set-SmbShare.md
  docset/winserver2012r2-ps/smbshare/Set-SmbShare.md
Labels: In review

#1400 Update set-smbclientconfiguration.md
  docset/windows/smbshare/set-smbclientconfiguration.md
  docset/winserver2012r2-ps/smbshare/Set-SmbClientConfiguration.md
Labels: In review

#1399 Update add-neteventpacketcaptureprovider.md
  docset/windows/neteventpacketcapture/add-neteventpacketcaptureprovider.md
  docset/winserver2012r2-ps/neteventpacketcapture/Add-NetEventPacketCaptureProvider.md
Labels: In review

#1371 Update Grant-SmbShareAccess.md
  docset/winserver2012-ps/smbshare/Grant-SmbShareAccess.md
  docset/winserver2012r2-ps/smbshare/Grant-SmbShareAccess.md
Labels: In review

#1393 Update Get-NetTCPConnection.md
  docset/winserver2012r2-ps/nettcpip/Get-NetTCPConnection.md
Labels: In review, SignOff

#1384 Update Get-DtcAdvancedHostSetting.md
  docset/winserver2012r2-ps/msdtc/Get-DtcAdvancedHostSetting.md
Labels: In review, SignOff

#1372 Add cmdlets description in Hyper-V.md
  docset/winserver2012-ps/hyper-v/Hyper-V.md
Labels: In review, SignOff

#1370 Update Get-SmbClientNetworkInterface.md
  docset/winserver2012-ps/smbshare/Get-SmbClientNetworkInterface.md
  docset/winserver2012r2-ps/smbshare/Get-SmbClientNetworkInterface.md
Labels: In review, SignOff

#1369 Update Get-SmbServerNetworkInterface.md
  docset/winserver2012-ps/smbshare/Get-SmbServerNetworkInterface.md
  docset/winserver2012r2-ps/smbshare/Get-SmbServerNetworkInterface.md
Labels: In review, SignOff

#1383 Update Add-DtcClusterTMMapping.md
  docset/winserver2012r2-ps/msdtc/Add-DtcClusterTMMapping.md
Labels: In review, SignOff

#1368 Update Block-SmbShareAccess.md
  docset/winserver2012-ps/smbshare/Block-SmbShareAccess.md
  docset/winserver2012r2-ps/smbshare/Block-SmbShareAccess.md
Labels: In review, SignOff

#1315 Update StartScreen.md
  docset/winserver2012r2-ps/startscreen/StartScreen.md
Labels: In review, SignOff

#1367 Update Close-SmbOpenFile.md
  docset/winserver2012-ps/smbshare/Close-SmbOpenFile.md
  docset/winserver2012r2-ps/smbshare/Close-SmbOpenFile.md
Labels: In review, SignOff

#1366 Update Close-SmbSession.md
  docset/winserver2012-ps/smbshare/Close-SmbSession.md
  docset/winserver2012r2-ps/smbshare/Close-SmbSession.md
Labels: In review, SignOff

#1365 Update Get-SmbConnection.md
  docset/winserver2012-ps/smbshare/Get-SmbConnection.md
  docset/winserver2012r2-ps/smbshare/Get-SmbConnection.md
Labels: In review, SignOff

#1354 Update Get-SmbShareAccess.md
  docset/winserver2012-ps/smbshare/Get-SmbShareAccess.md
  docset/winserver2012r2-ps/smbshare/Get-SmbShareAccess.md
Labels: In review, SignOff

#1364 Update Get-SmbMultichannelConnection.md
  docset/winserver2012-ps/smbshare/Get-SmbMultichannelConnection.md
  docset/winserver2012r2-ps/smbshare/Get-SmbMultichannelConnection.md
Labels: In review, SignOff

#1337 Update ServerManager.md
  docset/winserver2012-ps/servermanager/ServerManager.md
  docset/winserver2012r2-ps/servermanager/ServerManager.md
Labels: In review, SignOff

#1385 Update Get-DtcAdvancedSetting.md
  docset/winserver2012r2-ps/msdtc/Get-DtcAdvancedSetting.md
Labels: In review, SignOff

#1380 Add Wait parameter description 2012R2/2016 version
  docset/windows/failoverclusters/Reset-ClusterVMMonitoredState.md
  docset/winserver2012r2-ps/failoverclusters/Reset-ClusterVMMonitoredState.md
Labels: In review, SignOff

#1381 Add ForceDrain description in 2012 Version
  docset/windows/failoverclusters/Suspend-ClusterNode.md
  docset/winserver2012-ps/failoverclusters/Suspend-ClusterNode.md
  docset/winserver2012r2-ps/failoverclusters/Suspend-ClusterNode.md
Labels: In review, SignOff

#1378 Add Wait parameter description.
  docset/windows/failoverclusters/Stop-Cluster.md
  docset/winserver2012r2-ps/failoverclusters/Stop-Cluster.md
Labels: In review, SignOff

#1444 Update Get-NetTCPSetting.md
  docset/winserver2012r2-ps/msdtc/Add-DtcClusterTMMapping.md
  docset/winserver2012r2-ps/nettcpip/Get-NetTCPSetting.md
Labels: In review, SignOff

#1453 Update Set-SmbServerConfiguration.md
  docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md
Labels: In review, SignOff

#1404 Update Get-NetEventVmSwitch.md
  docset/winserver2012r2-ps/neteventpacketcapture/Get-NetEventVmSwitch.md
Labels: In review, SignOff

#1405 Update Set-NetEventPacketCaptureProvider.md
  docset/winserver2012r2-ps/neteventpacketcapture/Set-NetEventPacketCaptureProvider.md
Labels: In review, SignOff

#1406 Update Set-NetEventProvider.md
  docset/winserver2012r2-ps/neteventpacketcapture/Set-NetEventProvider.md
Labels: In review, SignOff

#1408 Update Start-NetEventSession.md
  docset/winserver2012r2-ps/neteventpacketcapture/Start-NetEventSession.md
Labels: In review, SignOff

#1410 Update New-NetEventSession.md
  docset/winserver2012r2-ps/neteventpacketcapture/New-NetEventSession.md
Labels: In review, SignOff

#1443 Update Set-DtcClusterTMMapping.md
  docset/winserver2012r2-ps/msdtc/Set-DtcClusterTMMapping.md
Labels: In review, SignOff

#1438 Update Remove-DtcClusterTMMapping.md
  docset/winserver2012r2-ps/msdtc/Remove-DtcClusterTMMapping.md
Labels: In review, SignOff

#1434 Update Get-DtcTransactionsStatistics.md
  docset/winserver2012r2-ps/msdtc/Get-DtcTransactionsStatistics.md
Labels: In review, SignOff

#1412 Update Remove-NetEventPacketCaptureProvider.md
  docset/winserver2012r2-ps/neteventpacketcapture/Remove-NetEventPacketCaptureProvider.md
Labels: In review, SignOff

#1415 Update Remove-NetEventSession.md
  docset/winserver2012r2-ps/neteventpacketcapture/Remove-NetEventSession.md
Labels: In review, SignOff

#1417 Update Remove-NetEventVmSwitch.md
  docset/winserver2012r2-ps/neteventpacketcapture/Remove-NetEventVmSwitch.md
Labels: In review, SignOff

#1420 Update Add-NetEventProvider.md
  docset/winserver2012r2-ps/neteventpacketcapture/Add-NetEventProvider.md
Labels: In review, SignOff

#1422 Update Add-NetEventVmSwitch.md
  docset/winserver2012r2-ps/neteventpacketcapture/Add-NetEventVmSwitch.md
Labels: SignOff

#1424 Update Get-NetEventPacketCaptureProvider.md
  docset/winserver2012r2-ps/neteventpacketcapture/Get-NetEventPacketCaptureProvider.md
Labels: SignOff

#1427 Update Get-NetEventSession.md
  docset/winserver2012r2-ps/neteventpacketcapture/Get-NetEventSession.md
Labels: In review, SignOff

#1436 Update Get-DtcTransactionsTraceSetting.md
  docset/winserver2012r2-ps/msdtc/Get-DtcTransactionsTraceSetting.md
Labels: In review, SignOff

#1437 Update Install-Dtc.md
  docset/winserver2012r2-ps/msdtc/Install-Dtc.md
Labels: SignOff

#1439 Update Reset-DtcLog.md
  docset/winserver2012r2-ps/msdtc/Reset-DtcLog.md
Labels: In review, SignOff

#1441 Update Set-DtcAdvancedSetting.md
  docset/winserver2012r2-ps/msdtc/Set-DtcAdvancedSetting.md
Labels: In review, SignOff

#1442 Update Set-DtcClusterDefault.md
  docset/winserver2012r2-ps/msdtc/Set-DtcClusterDefault.md
Labels: In review, SignOff

#1447 Update Initialize-RmsCryptoMode2.md
  docset/winserver2012-ps/adrmsadmin/Initialize-RmsCryptoMode2.md
  docset/winserver2012r2-ps/adrmsadmin/Initialize-RmsCryptoMode2.md
Labels: In review, SignOff

#1407 Update Set-NetEventSession.md
  docset/winserver2012r2-ps/neteventpacketcapture/Set-NetEventSession.md
Labels: SignOff

#1411 Update Remove-NetEventNetworkAdapter.md
  docset/winserver2012r2-ps/neteventpacketcapture/Remove-NetEventNetworkAdapter.md
Labels: In review, SignOff

#1409 Update Stop-NetEventSession.md
  docset/winserver2012r2-ps/neteventpacketcapture/Stop-NetEventSession.md
Labels: In review, SignOff

#1414 Update Remove-NetEventProvider.md
  docset/winserver2012r2-ps/neteventpacketcapture/Remove-NetEventProvider.md
Labels: In review, SignOff

#1416 Update Remove-NetEventVmNetworkAdapter.md
  docset/winserver2012r2-ps/neteventpacketcapture/Remove-NetEventVmNetworkAdapter.md
Labels: In review, SignOff

#1419 Update Add-NetEventPacketCaptureProvider.md
  docset/winserver2012r2-ps/neteventpacketcapture/Add-NetEventPacketCaptureProvider.md
Labels: In review, SignOff

#1418 Update Add-NetEventNetworkAdapter.md
  docset/winserver2012r2-ps/neteventpacketcapture/Add-NetEventNetworkAdapter.md
Labels: In review, SignOff

#1421 Update Add-NetEventVmNetworkAdapter.md
  docset/winserver2012r2-ps/neteventpacketcapture/Add-NetEventVmNetworkAdapter.md
Labels: In review, SignOff

#1423 Update Get-NetEventNetworkAdapter.md
  docset/winserver2012r2-ps/neteventpacketcapture/Get-NetEventNetworkAdapter.md
Labels: In review, SignOff

#1425 Update Get-NetEventProvider.md
  docset/winserver2012r2-ps/neteventpacketcapture/Get-NetEventProvider.md
Labels: In review, SignOff

#1428 Update Get-NetEventVmNetworkAdapter.md
  docset/winserver2012r2-ps/neteventpacketcapture/Get-NetEventVmNetworkAdapter.md
Labels: In review, SignOff

#1440 Update Set-DtcAdvancedHostSetting.md
  docset/winserver2012r2-ps/msdtc/Set-DtcAdvancedHostSetting.md
Labels: In review, SignOff

#1456 Update Set-VpnS2SInterface.md
  docset/windows/remoteaccess/Set-VpnS2SInterface.md
Labels: In review, SignOff

#1435 Update Write-DtcTransactionsTraceSession.md
  docset/winserver2012r2-ps/msdtc/Write-DtcTransactionsTraceSession.md
Labels: In review, SignOff

#1457 Update Get-BgpStatistics.md
  docset/windows/remoteaccess/Get-BgpStatistics.md
Labels: In review, SignOff

#1458 Fix missing description and http to https links
  docset/windows/dhcpserver/Get-DhcpServerv4FreeIPAddress.md
  docset/winserver2012-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md
  docset/winserver2012r2-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md
Labels: In review

#1459 Fix missing description and http --> https
  docset/windows/dhcpserver/Get-DhcpServerv6FreeIPAddress.md
  docset/winserver2012-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md
  docset/winserver2012r2-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md
Labels: In review, SignOff

#1460 Fix missing description and http --> https
  docset/windows/dhcpserver/Get-DhcpServerv6Statistics.md
  docset/winserver2012-ps/dhcpserver/Get-DhcpServerv6Statistics.md
  docset/winserver2012r2-ps/dhcpserver/Get-DhcpServerv6Statistics.md
Labels: In review, SignOff

#1461 Fix missing description and http --> https
  docset/windows/dhcpserver/Get-DhcpServerVersion.md
  docset/winserver2012-ps/dhcpserver/Get-DhcpServerVersion.md
  docset/winserver2012r2-ps/dhcpserver/Get-DhcpServerVersion.md
Labels: In review, SignOff

#1469 Update Get-DtcClusterTMMapping.md
  docset/winserver2012r2-ps/msdtc/Get-DtcClusterTMMapping.md
Labels: In review, SignOff

#1470 Update Get-DtcNetworkSetting.md
  docset/winserver2012r2-ps/msdtc/Get-DtcNetworkSetting.md
Labels: In review, SignOff

#1462 Fix AsJob parameter description and http to https
  docset/windows/deduplication/Disable-DedupVolume.md
  docset/windows/deduplication/Enable-DedupVolume.md
  docset/windows/deduplication/Expand-DedupFile.md
  docset/windows/deduplication/Get-DedupJob.md
  docset/windows/deduplication/Get-DedupMetadata.md
  docset/windows/deduplication/Get-DedupSchedule.md
  docset/windows/deduplication/Get-DedupStatus.md
  docset/windows/deduplication/Get-DedupVolume.md
  docset/windows/deduplication/Measure-DedupFileMetadata.md
  docset/windows/deduplication/New-DedupSchedule.md
  docset/windows/deduplication/Remove-DedupSchedule.md
  docset/windows/deduplication/Set-DedupSchedule.md
  docset/windows/deduplication/Set-DedupVolume.md
  docset/windows/deduplication/Start-DedupJob.md
  docset/windows/deduplication/Stop-DedupJob.md
  docset/windows/deduplication/Update-DedupStatus.md
  docset/winserver2012-ps/deduplication/Disable-DedupVolume.md
  docset/winserver2012-ps/deduplication/Enable-DedupVolume.md
  docset/winserver2012-ps/deduplication/Get-DedupJob.md
  docset/winserver2012-ps/deduplication/Get-DedupMetadata.md
  docset/winserver2012-ps/deduplication/Get-DedupSchedule.md
  docset/winserver2012-ps/deduplication/Get-DedupStatus.md
  docset/winserver2012-ps/deduplication/Get-DedupVolume.md
  docset/winserver2012-ps/deduplication/Measure-DedupFileMetadata.md
  docset/winserver2012-ps/deduplication/New-DedupSchedule.md
  docset/winserver2012-ps/deduplication/Remove-DedupSchedule.md
  docset/winserver2012-ps/deduplication/Set-DedupSchedule.md
  docset/winserver2012-ps/deduplication/Set-DedupVolume.md
  docset/winserver2012-ps/deduplication/Start-DedupJob.md
  docset/winserver2012-ps/deduplication/Stop-DedupJob.md
  docset/winserver2012-ps/deduplication/Update-DedupStatus.md
  docset/winserver2012r2-ps/deduplication/Disable-DedupVolume.md
  docset/winserver2012r2-ps/deduplication/Enable-DedupVolume.md
  docset/winserver2012r2-ps/deduplication/Expand-DedupFile.md
  docset/winserver2012r2-ps/deduplication/Get-DedupJob.md
  docset/winserver2012r2-ps/deduplication/Get-DedupMetadata.md
  docset/winserver2012r2-ps/deduplication/Get-DedupSchedule.md
  docset/winserver2012r2-ps/deduplication/Get-DedupStatus.md
  docset/winserver2012r2-ps/deduplication/Get-DedupVolume.md
  docset/winserver2012r2-ps/deduplication/Measure-DedupFileMetadata.md
  docset/winserver2012r2-ps/deduplication/New-DedupSchedule.md
  docset/winserver2012r2-ps/deduplication/Remove-DedupSchedule.md
  docset/winserver2012r2-ps/deduplication/Set-DedupSchedule.md
  docset/winserver2012r2-ps/deduplication/Set-DedupVolume.md
  docset/winserver2012r2-ps/deduplication/Start-DedupJob.md
  docset/winserver2012r2-ps/deduplication/Stop-DedupJob.md
  docset/winserver2012r2-ps/deduplication/Update-DedupStatus.md
Labels: In review, SignOff

#1474 Add missing description on parameters.
  docset/windows/storage/Get-PhysicalDisk.md
  docset/winserver2012-ps/storage/Get-PhysicalDisk.md
  docset/winserver2012r2-ps/storage/Get-PhysicalDisk.md
Labels: In review, SignOff

#1476 Update Get-DtcLog.md
  docset/winserver2012r2-ps/msdtc/Get-DtcLog.md
Labels: In review, SignOff

#1477 Update Get-DtcTransaction.md
  docset/winserver2012r2-ps/msdtc/Get-DtcTransaction.md
Labels: In review, SignOff

#1475 Update Get-DtcDefault.md
  docset/winserver2012r2-ps/msdtc/Get-DtcDefault.md
Labels: In review, SignOff

#1478 Update Get-Dtc.md
  docset/winserver2012r2-ps/msdtc/Get-Dtc.md
Labels: In review, SignOff

#1486 Fix Markdown formatting for CimSession links
  docset/winserver2012r2-ps/msdtc/Get-DtcLog.md
  docset/winserver2012r2-ps/msdtc/Get-DtcTransaction.md
Labels: In review

#1489 Update Get-BgpStatistics.md
  docset/windows/remoteaccess/Get-BgpStatistics.md
Labels: In review, SignOff

#1503 Update Get-DtcTransactionsTraceSession.md
  docset/winserver2012r2-ps/msdtc/Get-DtcTransactionsTraceSession.md
Labels: In review, SignOff

#1500 Update Stop-Dtc.md
  docset/winserver2012r2-ps/msdtc/Stop-Dtc.md
Labels: In review, SignOff

#1498 Update Start-Dtc.md
  docset/winserver2012r2-ps/msdtc/Start-Dtc.md
Labels: In review, SignOff

#1495 Update Set-DtcTransaction.md
  docset/winserver2012r2-ps/msdtc/Set-DtcTransaction.md
Labels: In review, SignOff

#1493 Update Set-DtcLog.md
  docset/winserver2012r2-ps/msdtc/Set-DtcLog.md
Labels: In review, SignOff

#1484 Update Get-WmsSession.md
  docset/windows/multipoint/Get-WmsSession.md
Labels: In review, SignOff

#1483 Update Set-WmsStation.md
  docset/windows/multipoint/Set-WmsStation.md
Labels: In review, SignOff

#1482 Update Set-WmsSystem.md
  docset/windows/multipoint/Set-WmsSystem.md
Labels: In review, SignOff

#1479 Add example 9
  docset/windows/pkiclient/New-SelfSignedCertificate.md
Labels: In review, SignOff

#1473 Update Get-BgpCustomRoute.md
  docset/windows/remoteaccess/Get-BgpCustomRoute.md
Labels: In review, SignOff

#1472 Update Get-BgpPeer.md
  docset/windows/remoteaccess/Get-BgpPeer.md
Labels: In review, SignOff

#1471 Update Get-BgpRoutingPolicy.md
  docset/windows/remoteaccess/Get-BgpRoutingPolicy.md
Labels: In review, SignOff

#1467 Update test-mbamwebapplication.md
  docset/mdop/mbam/test-mbamwebapplication.md
Labels: In review, SignOff

#1466 Update enable-mbamwebapplication.md
  docset/mdop/mbam/enable-mbamwebapplication.md
Labels: In review, SignOff

#1465 Update get-appvvirtualprocess.md
  docset/mdop/appvclient/get-appvvirtualprocess.md
Labels: In review, SignOff

#1455 Update Unregister-SmisProvider.md
  docset/windows/smisconfig/Unregister-SmisProvider.md
Labels: In review, SignOff

#1448 Update Get-DedupVolume.md
  docset/winserver2012-ps/deduplication/Get-DedupVolume.md
Labels: In review, SignOff

#1386 Update Get-DtcClusterDefault.md
  docset/winserver2012r2-ps/msdtc/Get-DtcClusterDefault.md
Labels: In review, SignOff

#1485 Update SetDnsServerDiagnostics.md EventLogLevel Description
  docset/windows/dnsserver/Set-DnsServerDiagnostics.md
Labels: In review, SignOff

#1512 Patch 4
  docset/winserver2012-ps/dnsserver/Set-DnsServerDiagnostics.md
  docset/winserver2012r2-ps/dnsserver/Set-DnsServerDiagnostics.md
Labels: In review, SignOff

#1504 Update Set-MsmqQueueManager.md
  docset/windows/msmq/Set-MsmqQueueManager.md
  docset/winserver2012r2-ps/msmq/Set-MsmqQueueManager.md
Labels: In review, SignOff

#1497 Update Set-DtcTransactionsTraceSetting.md
  docset/winserver2012r2-ps/msdtc/Set-DtcTransactionsTraceSetting.md
Labels: In review, SignOff

#1505 Update New-MsmqMessage.md
  docset/windows/msmq/New-MsmqMessage.md
  docset/winserver2012-ps/msmq/New-MsmqMessage.md
  docset/winserver2012r2-ps/msmq/New-MsmqMessage.md
Labels: In review, SignOff

#1506 Update Send-MsmqQueue.md
  docset/windows/msmq/Send-MsmqQueue.md
  docset/winserver2012r2-ps/msmq/Send-MsmqQueue.md
Labels: In review, SignOff

#1492 Update Set-DtcDefault.md
  docset/winserver2012r2-ps/msdtc/Set-DtcDefault.md
Labels: In review, SignOff

#1494 Update Set-DtcNetworkSetting.md
  docset/winserver2012r2-ps/msdtc/Set-DtcNetworkSetting.md
Labels: In review, SignOff

#1496 Update Set-DtcTransactionsTraceSession.md
  docset/winserver2012r2-ps/msdtc/Set-DtcTransactionsTraceSession.md
Labels: In review, SignOff

#1499 Update Start-DtcTransactionsTraceSession.md
  docset/winserver2012r2-ps/msdtc/Start-DtcTransactionsTraceSession.md
Labels: In review, SignOff

#1501 Update Stop-DtcTransactionsTraceSession.md
  docset/winserver2012r2-ps/msdtc/Stop-DtcTransactionsTraceSession.md
Labels: In review, SignOff

#1502 Update Uninstall-Dtc.md
  docset/winserver2012r2-ps/msdtc/Uninstall-Dtc.md
Labels: In review, SignOff

#1509 Resolves #1359
  docset/windows/adfs/Set-AdfsCertificate.md
  docset/winserver2012-ps/adfs/Set-ADFSCertificate.md
  docset/winserver2012r2-ps/adfs/Set-AdfsCertificate.md
Labels: In review, SignOff

#1508 Resolves #1307
  docset/windows/printmanagement/Get-PrintConfiguration.md
  docset/winserver2012-ps/printmanagement/Get-PrintConfiguration.md
  docset/winserver2012r2-ps/printmanagement/Get-PrintConfiguration.md
Labels: In review, SignOff

#1510 Resolves #1382
  docset/windows/netsecurity/Set-NetFirewallAddressFilter.md
  docset/winserver2012-ps/netsecurity/Set-NetFirewallAddressFilter.md
  docset/winserver2012r2-ps/netsecurity/Set-NetFirewallAddressFilter.md
Labels: In review, SignOff

#1521 Remove Spurious Sentence from Install-AdfsFarm.md
  docset/windows/adfs/Install-AdfsFarm.md
Labels: In review, SignOff

#1529 Dansimp patch 1
  docset/windows/processmitigations/Set-ProcessMitigation.md
Labels: SignOff

#1531 Update Set-DnsServerCache.md
  docset/windows/dnsserver/Set-DnsServerCache.md
Labels: In review, SignOff

#1532 Update Set-DnsServerDsSetting.md
  docset/windows/dnsserver/Set-DnsServerDsSetting.md
Labels: In review, SignOff

#1533 Update Set-DnsServerForwarder.md
  docset/windows/dnsserver/Set-DnsServerForwarder.md
Labels: In review, SignOff

#1534 Update Set-DnsServerGlobalQueryBlockList.md
  docset/windows/dnsserver/Set-DnsServerGlobalQueryBlockList.md
Labels: In review, SignOff

#1535 Update Set-DnsServerSetting.md
  docset/windows/dnsserver/Set-DnsServerSetting.md
Labels: In review, SignOff

#1536 Update Add-DnsServerDirectoryPartition.md
  docset/windows/dnsserver/Add-DnsServerDirectoryPartition.md
Labels: In review, SignOff

#1537 Update Get-DnsServerStatistics.md
  docset/windows/dnsserver/Get-DnsServerStatistics.md
Labels: In review, SignOff

#1530 Update Set-DnsServerDiagnostics.md
  docset/windows/dnsserver/Set-DnsServerDiagnostics.md
  docset/winserver2012-ps/dnsserver/Set-DnsServerDiagnostics.md
  docset/winserver2012r2-ps/dnsserver/Set-DnsServerDiagnostics.md
Labels: In review, SignOff

#1523 Link to option descriptions
  docset/windows/configci/Set-RuleOption.md
Labels: In review, SignOff

#1545 Update Install-AdfsFarm and Add-AdfsFarmNode
  docset/windows/adfs/Add-AdfsFarmNode.md
  docset/windows/adfs/Install-AdfsFarm.md
  docset/winserver2012r2-ps/adfs/Add-AdfsFarmNode.md
  docset/winserver2012r2-ps/adfs/Install-AdfsFarm.md
Labels: In review, SignOff

#1548 Update Set-AdfsGlobalWebContent.md
  docset/windows/adfs/Set-AdfsGlobalWebContent.md
  docset/winserver2012r2-ps/adfs/Set-AdfsGlobalWebContent.md
Labels: In review, SignOff

#1549 Update Get-AdfsGlobalWebContent
  docset/windows/adfs/Get-AdfsGlobalWebContent.md
Labels: In review, SignOff

#1550 Update NetworkTransition.md
  docset/winserver2012-ps/networktransition/NetworkTransition.md
Labels: In review, SignOff

#1556 Update Get-WebApplicationProxyConfiguration
  docset/windows/webapplicationproxy/Get-WebApplicationProxyConfiguration.md
Labels: In review, SignOff

#1562 Resolves #1544
  docset/windows/dfsr/Get-DfsrState.md
  docset/winserver2012r2-ps/dfsr/Get-DfsrState.md
Labels: In review, SignOff

#1561 Resolves #1555
  docset/windows/tls/Enable-TlsEccCurve.md
Labels: In review, SignOff

#1564 Resolves #1541
  docset/windows/webapplicationproxy/Set-WebApplicationProxyConfiguration.md
  docset/winserver2012r2-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md
Labels: In review, SignOff

#1565 Fix name of EventTracingManagement module
  docset/windows/eventtracingmanagement/Add-EtwTraceProvider.md
  docset/windows/eventtracingmanagement/EventTracingManagement.md
  docset/windows/eventtracingmanagement/Get-AutologgerConfig.md
  docset/windows/eventtracingmanagement/Get-EtwTraceProvider.md
  docset/windows/eventtracingmanagement/Get-EtwTraceSession.md
  docset/windows/eventtracingmanagement/New-AutologgerConfig.md
  docset/windows/eventtracingmanagement/New-EtwTraceSession.md
  docset/windows/eventtracingmanagement/Remove-AutologgerConfig.md
  docset/windows/eventtracingmanagement/Remove-EtwTraceProvider.md
  docset/windows/eventtracingmanagement/Save-EtwTraceSession.md
  docset/windows/eventtracingmanagement/Send-EtwTraceSession.md
  docset/windows/eventtracingmanagement/Set-AutologgerConfig.md
  docset/windows/eventtracingmanagement/Set-EtwTraceProvider.md
  docset/windows/eventtracingmanagement/Start-EtwTraceSession.md
  docset/windows/eventtracingmanagement/Stop-EtwTraceSession.md
  docset/windows/eventtracingmanagement/Update-EtwTraceSession.md
Labels: In review, SignOff
