Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2019-12, with the labels that each got.

#1593 Adfs Module: Improve Inputs and Outputs for the AdfsClient Cmdlets
  docset/windows/adfs/Add-AdfsClient.md
  docset/windows/adfs/Disable-AdfsClient.md
  docset/windows/adfs/Enable-AdfsClient.md
  docset/windows/adfs/Get-AdfsClient.md
  docset/windows/adfs/Remove-AdfsClient.md
  docset/windows/adfs/Set-AdfsClient.md
Labels: In review, SignOff

#1606 Enable-AdfsDeviceRegistration: Fix URL Link
  docset/windows/adfs/Enable-AdfsDeviceRegistration.md
Labels: In review, SignOff

#1575 Adfs Module: Improve Inputs and Outputs for the AdfsCertificate Cmdlets
  docset/windows/adfs/Add-AdfsCertificate.md
  docset/windows/adfs/Get-AdfsCertificate.md
  docset/windows/adfs/Remove-AdfsCertificate.md
  docset/windows/adfs/Set-AdfsCertificate.md
  docset/windows/adfs/Update-AdfsCertificate.md
Labels: In review, SignOff

#1586 Adfs Module: Improve Inputs and Outputs for the AdfsClaimsProviderTrust Cmdlets
  docset/windows/adfs/Add-AdfsClaimsProviderTrust.md
  docset/windows/adfs/Disable-AdfsClaimsProviderTrust.md
  docset/windows/adfs/Enable-AdfsClaimsProviderTrust.md
  docset/windows/adfs/Get-AdfsClaimsProviderTrust.md
  docset/windows/adfs/Remove-AdfsClaimsProviderTrust.md
  docset/windows/adfs/Set-AdfsClaimsProviderTrust.md
  docset/windows/adfs/Update-AdfsClaimsProviderTrust.md
Labels: In review, SignOff

#1588 add reference to parameters
  docset/winserver2012-ps/msonlinebackup/New-OBRetentionPolicy.md
Labels: In review, SignOff

#1609 Clarify that Get-AppLockerPolicy only works for GP
  docset/windows/applocker/Get-AppLockerPolicy.md
Labels: In review

#1630 Update Set-VMComPort.md (via #1610)
  docset/windows/hyper-v/Set-VMComPort.md
Labels: In review, SignOff

#1623 Fix major typo: It is "UpdateServices", not "WSUS"
  .openpublishing.redirection.json
  docset/windows/updateservices/Add-WsusComputer.md
  docset/windows/updateservices/Add-WsusDynamicCategory.md
  docset/windows/updateservices/Approve-WsusUpdate.md
  docset/windows/updateservices/Deny-WsusUpdate.md
  docset/windows/updateservices/Get-WsusClassification.md
  docset/windows/updateservices/Get-WsusComputer.md
  docset/windows/updateservices/Get-WsusDynamicCategory.md
  docset/windows/updateservices/Get-WsusProduct.md
  docset/windows/updateservices/Get-WsusServer.md
  docset/windows/updateservices/Get-WsusUpdate.md
  docset/windows/updateservices/Invoke-WsusServerCleanup.md
  docset/windows/updateservices/Remove-WsusDynamicCategory.md
  docset/windows/updateservices/Set-WsusClassification.md
  docset/windows/updateservices/Set-WsusDynamicCategory.md
  docset/windows/updateservices/Set-WsusProduct.md
  docset/windows/updateservices/Set-WsusServerSynchronization.md
  docset/windows/updateservices/UpdateServices.md
Labels: help wanted
