Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-05, with the labels that each got.

#1912 updating table under -SubmitSamplesConsent
  docset/windows/defender/Set-MpPreference.md
Labels: Microsoft submitter

#1925 "May the 4th be with You" Publish 5/4/2020 10:36 AM PST
  docset/windows/defender/Set-MpPreference.md
Labels: Microsoft submitter

#1850 Correct -PolicyStore path example
  docset/windows/netsecurity/Set-NetFirewallProfile.md
Labels: In review, Sign off

#1910 Update New-ScheduledTaskSettingsSet.md
  docset/windows/scheduledtasks/New-ScheduledTaskSettingsSet.md
Labels: In review, Sign off

#1914 Fixed note on Get-ADUser.md
  docset/windows/addsadministration/Get-ADUser.md
Labels: In review, Sign off

#1888 Get-MsmqQueue Example: Message count for all local queues
  docset/windows/msmq/Get-MsmqQueue.md
Labels: In review, Sign off

#1896 Update Get-ADUser.md
  docset/windows/addsadministration/Get-ADUser.md
Labels: In review, Sign off

#1926 Publish 5/6/2020 10:30 AM PST
  docset/windows/addsadministration/Get-ADUser.md
  docset/windows/msmq/Get-MsmqQueue.md
  docset/windows/netsecurity/Set-NetFirewallProfile.md
  docset/windows/scheduledtasks/New-ScheduledTaskSettingsSet.md
Labels: Microsoft submitter

#1921 Update New-NetQosPolicy.md
  docset/windows/netqos/New-NetQosPolicy.md
Labels: In review, Sign off

#1922 Update Get-ADFSEndpoint.md
  docset/winserver2012-ps/adfs/Get-ADFSEndpoint.md
Labels: In review, Sign off

#1928 Publish 5/7/2020 3:30 PM PST
  docset/windows/netqos/New-NetQosPolicy.md
  docset/winserver2012-ps/adfs/Get-ADFSEndpoint.md
Labels: Microsoft submitter

#1927 Add DataCenterBridging reference to NetLldpModule overview
  docset/windows/netldpagent/NetLldpAgent.md
Labels: In review, Sign off

#1931 Resolves #1851
  docset/windows/bitlocker/Get-BitLockerVolume.md
Labels: In review, Sign off

#1920 Incorrect Default value listed
  docset/windows/netsecurity/New-NetFirewallRule.md
Labels: In review, Sign off

#1913 Update New-FsrmStorageReport.md
  docset/windows/fileserverresourcemanager/New-FsrmStorageReport.md
Labels: In review, Sign off

#1935 Publish 5/11/2020 10:30 AM PT
  docset/windows/bitlocker/Get-BitLockerVolume.md
  docset/windows/fileserverresourcemanager/New-FsrmStorageReport.md
  docset/windows/netldpagent/NetLldpAgent.md
  docset/windows/netsecurity/New-NetFirewallRule.md
Labels: Admin review, Microsoft submitter

#1932 Resolves #1596
  docset/windows/failoverclusters/Add-ClusterResourceDependency.md
  docset/winserver2012-ps/failoverclusters/Add-ClusterResourceDependency.md
  docset/winserver2012r2-ps/failoverclusters/Add-ClusterResourceDependency.md
Labels: In review, Sign off

#1938 Publish 05/11/2020 3:30
  docset/windows/failoverclusters/Add-ClusterResourceDependency.md
  docset/winserver2012-ps/failoverclusters/Add-ClusterResourceDependency.md
  docset/winserver2012r2-ps/failoverclusters/Add-ClusterResourceDependency.md
Labels: Microsoft submitter

#1946 Resolves #1855
  docset/windows/vpnclient/Set-VpnConnectionProxy.md
  docset/winserver2012-ps/vpnclient/Set-VpnConnectionProxy.md
  docset/winserver2012r2-ps/vpnclient/Set-VpnConnectionProxy.md
Labels: In review, Sign off

#1951 Publish 5/13/2020 10:30 AM PT
  docset/windows/vpnclient/Set-VpnConnectionProxy.md
  docset/winserver2012-ps/vpnclient/Set-VpnConnectionProxy.md
  docset/winserver2012r2-ps/vpnclient/Set-VpnConnectionProxy.md
Labels: Microsoft submitter

#1942 Update Set-ADDefaultDomainPasswordPolicy.md
  docset/windows/addsadministration/Set-ADDefaultDomainPasswordPolicy.md
  docset/winserver2012-ps/activedirectory/Set-ADDefaultDomainPasswordPolicy.md
  docset/winserver2012r2-ps/addsadministration/Set-ADDefaultDomainPasswordPolicy.md
Labels: In review, Sign off

#1953 Publish 5/14/2020 10:30 AM PT
  docset/windows/addsadministration/Set-ADDefaultDomainPasswordPolicy.md
  docset/winserver2012-ps/activedirectory/Set-ADDefaultDomainPasswordPolicy.md
  docset/winserver2012r2-ps/addsadministration/Set-ADDefaultDomainPasswordPolicy.md
Labels: Microsoft submitter

#1944 Update Remove-AppxPackage.md
  docset/windows/appx/Remove-AppxPackage.md
Labels: In review, Sign off

#1952 Update Remove-MpPreference.md
  docset/windows/defender/Remove-MpPreference.md
Labels: In review, Sign off

#1940 Update Add-DnsServerQueryResolutionPolicy.md
  docset/windows/dnsserver/Add-DnsServerQueryResolutionPolicy.md
Labels: In review, Sign off

#1956 Update redirection files for wsus module
  .openpublishing.redirection.json
Labels: Microsoft submitter, Sign off

#1958 Resolves #1721
  docset/windows/iisadministration/Get-IISAppPool.md
Labels: In review, Sign off

#1960 Resolves #1587
  docset/windows/dhcpserver/Import-DhcpServer.md
  docset/winserver2012-ps/dhcpserver/Import-DhcpServer.md
  docset/winserver2012r2-ps/dhcpserver/Import-DhcpServer.md
Labels: In review, Sign off

#1961 Resolves #1759
  docset/windows/webadministration/Get-WebApplication.md
  docset/winserver2012-ps/webadminstration/Get-WebApplication.md
  docset/winserver2012r2-ps/webadministration/Get-WebApplication.md
Labels: In review, Sign off

#1963 Resolves #1732
  docset/windows/hyper-v/New-VM.md
  docset/winserver2012-ps/hyper-v/New-VM.md
  docset/winserver2012r2-ps/hyper-v/New-VM.md
Labels: In review, Sign off

#1966 Publish 5/18/2020 10:30 AM PT
  .openpublishing.redirection.json
  docset/windows/dhcpserver/Import-DhcpServer.md
  docset/windows/hyper-v/New-VM.md
  docset/windows/iisadministration/Get-IISAppPool.md
  docset/windows/webadministration/Get-WebApplication.md
  docset/winserver2012-ps/dhcpserver/Import-DhcpServer.md
  docset/winserver2012-ps/hyper-v/New-VM.md
  docset/winserver2012-ps/webadminstration/Get-WebApplication.md
  docset/winserver2012r2-ps/dhcpserver/Import-DhcpServer.md
  docset/winserver2012r2-ps/hyper-v/New-VM.md
  docset/winserver2012r2-ps/webadministration/Get-WebApplication.md
Labels: Admin review, Microsoft submitter

#1967 Update the maximum size of the cluster log to 2048 MB
  docset/windows/failoverclusters/Set-ClusterLog.md
Labels: Microsoft submitter

#1969 Publish 5/19/2020 10:30 AM PT
  docset/windows/failoverclusters/Set-ClusterLog.md
Labels: Microsoft submitter

#1975 Update Add-KdsRootKey.md
  docset/windows/kds/Add-KdsRootKey.md
  docset/winserver2012-ps/kds/Add-KdsRootKey.md
  docset/winserver2012r2-ps/kds/Add-KdsRootKey.md
Labels: In review, Sign off

#1970 Update Format-Volume.md
  docset/winserver2012-ps/storage/Format-Volume.md
  docset/winserver2012r2-ps/storage/Format-Volume.md
Labels: In review, Sign off

#1971 Update Test-AppLockerPolicy.md
  docset/windows/applocker/Test-AppLockerPolicy.md
  docset/winserver2012-ps/applocker/Test-AppLockerPolicy.md
  docset/winserver2012r2-ps/applocker/Test-AppLockerPolicy.md
Labels: In review, Sign off

#1974 Update Get-PrinterProperty.md
  docset/windows/printmanagement/Get-PrinterProperty.md
Labels: In review, Sign off

#1972 Update get-started.md
  docset/docs-conceptual/windows/get-started.md
Labels: In review, Sign off

#1981 Delete Add-OBFileSpec.md
  docset/winserver2012-ps/msonlinebackup/Add-OBFileSpec.md
Labels: Microsoft submitter

#1980 Publish 3:30 PM 05/21/2020
  docset/docs-conceptual/windows/get-started.md
  docset/windows/applocker/Test-AppLockerPolicy.md
  docset/windows/kds/Add-KdsRootKey.md
  docset/windows/printmanagement/Get-PrinterProperty.md
  docset/winserver2012-ps/applocker/Test-AppLockerPolicy.md
  docset/winserver2012-ps/kds/Add-KdsRootKey.md
  docset/winserver2012-ps/msonlinebackup/Add-OBFileSpec.md
  docset/winserver2012-ps/storage/Format-Volume.md
  docset/winserver2012r2-ps/applocker/Test-AppLockerPolicy.md
  docset/winserver2012r2-ps/kds/Add-KdsRootKey.md
  docset/winserver2012r2-ps/storage/Format-Volume.md
Labels: Microsoft submitter

#1982 Delete MSOnlineBackup files since it's published in a seperate repo
  docset/winserver2012-ps/msonlinebackup/Get-OBAllRecoveryPoints.md
  docset/winserver2012-ps/msonlinebackup/Get-OBAlternateBackupServer.md
  docset/winserver2012-ps/msonlinebackup/Get-OBCertificateListFromLocalStore.md
  docset/winserver2012-ps/msonlinebackup/Get-OBFileSpec.md
  docset/winserver2012-ps/msonlinebackup/Get-OBJob.md
  docset/winserver2012-ps/msonlinebackup/Get-OBMachineSetting.md
  docset/winserver2012-ps/msonlinebackup/Get-OBMachineUsage.md
  docset/winserver2012-ps/msonlinebackup/Get-OBNotification.md
  docset/winserver2012-ps/msonlinebackup/Get-OBPolicy.md
  docset/winserver2012-ps/msonlinebackup/Get-OBPolicyState.md
  docset/winserver2012-ps/msonlinebackup/Get-OBRecoverableItem.md
  docset/winserver2012-ps/msonlinebackup/Get-OBRecoverableSource.md
  docset/winserver2012-ps/msonlinebackup/Get-OBRecoveryService.md
  docset/winserver2012-ps/msonlinebackup/Get-OBRetentionPolicy.md
  docset/winserver2012-ps/msonlinebackup/Get-OBSchedule.md
  docset/winserver2012-ps/msonlinebackup/MSOnlineBackup.md
  docset/winserver2012-ps/msonlinebackup/New-OBFileSpec.md
  docset/winserver2012-ps/msonlinebackup/New-OBPagingContext.md
  docset/winserver2012-ps/msonlinebackup/New-OBPolicy.md
  docset/winserver2012-ps/msonlinebackup/New-OBRecoverableItem.md
  docset/winserver2012-ps/msonlinebackup/New-OBRecoveryOption.md
  docset/winserver2012-ps/msonlinebackup/New-OBRetentionPolicy.md
  docset/winserver2012-ps/msonlinebackup/New-OBSchedule.md
  docset/winserver2012-ps/msonlinebackup/Remove-OBFileSpec.md
  docset/winserver2012-ps/msonlinebackup/Remove-OBPolicy.md
  docset/winserver2012-ps/msonlinebackup/Rename-OBVolume.md
  docset/winserver2012-ps/msonlinebackup/Set-OBMachineSetting.md
  docset/winserver2012-ps/msonlinebackup/Set-OBPolicy.md
  docset/winserver2012-ps/msonlinebackup/Set-OBPolicyState.md
  docset/winserver2012-ps/msonlinebackup/Set-OBRetentionPolicy.md
  docset/winserver2012-ps/msonlinebackup/Set-OBSchedule.md
  docset/winserver2012-ps/msonlinebackup/Start-OBBackup.md
  docset/winserver2012-ps/msonlinebackup/Start-OBRecovery.md
  docset/winserver2012-ps/msonlinebackup/Start-OBRegistration.md
  docset/winserver2012-ps/msonlinebackup/Stop-OBJob.md
Labels: Microsoft submitter
