Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-08, with the labels that each got.

#2071 Update New-NpsRadiusClient.md
  docset/windows/nps/New-NpsRadiusClient.md
Labels: Microsoft submitter

#2072 Publish 8/4/2020
  docset/windows/nps/New-NpsRadiusClient.md
Labels: Microsoft submitter

#2081 Resolve #2047
  docset/windows/netsecurity/Set-NetIPsecMainModeCryptoSet.md
  docset/winserver2012-ps/netsecurity/Set-NetIPsecMainModeCryptoSet.md
  docset/winserver2012r2-ps/netsecurity/Set-NetIPsecMainModeCryptoSet.md
Labels: In review, Sign off

#2085 Publish 8/12/2020 10:30 AM PT
  docset/windows/netsecurity/Set-NetIPsecMainModeCryptoSet.md
  docset/winserver2012-ps/netsecurity/Set-NetIPsecMainModeCryptoSet.md
  docset/winserver2012r2-ps/netsecurity/Set-NetIPsecMainModeCryptoSet.md
Labels: Microsoft submitter

#2079 Resolves #2028
  docset/windows/hyper-v/Move-VM.md
  docset/winserver2012-ps/hyper-v/Move-VM.md
  docset/winserver2012r2-ps/hyper-v/Move-VM.md
Labels: In review, Sign off

#2077 Resolves #2052
  docset/windows/addsadministration/Remove-ADUser.md
  docset/winserver2012-ps/activedirectory/Remove-ADUser.md
  docset/winserver2012r2-ps/addsadministration/Remove-ADUser.md
Labels: In review, Sign off

#2084 Resolves #2059
  docset/windows/addsadministration/New-ADComputer.md
  docset/windows/addsadministration/New-ADServiceAccount.md
  docset/windows/addsadministration/New-ADUser.md
  docset/windows/addsadministration/Set-ADComputer.md
  docset/windows/addsadministration/Set-ADServiceAccount.md
  docset/windows/addsadministration/Set-ADUser.md
  docset/winserver2012-ps/activedirectory/New-ADComputer.md
  docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md
  docset/winserver2012-ps/activedirectory/New-ADUser.md
  docset/winserver2012-ps/activedirectory/Set-ADComputer.md
  docset/winserver2012-ps/activedirectory/Set-ADServiceAccount.md
  docset/winserver2012-ps/activedirectory/Set-ADUser.md
  docset/winserver2012r2-ps/addsadministration/New-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md
  docset/winserver2012r2-ps/addsadministration/New-ADUser.md
  docset/winserver2012r2-ps/addsadministration/Set-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/Set-ADServiceAccount.md
  docset/winserver2012r2-ps/addsadministration/Set-ADUser.md
Labels: In review, Sign off

#2073 Resolves #1891
  docset/windows/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md
Labels: In review, Sign off

#2076 Resolves #2045
  docset/windows/scheduledtasks/Disable-ScheduledTask.md
  docset/windows/scheduledtasks/Enable-ScheduledTask.md
  docset/windows/scheduledtasks/Export-ScheduledTask.md
  docset/windows/scheduledtasks/Get-ScheduledTask.md
  docset/windows/scheduledtasks/Get-ScheduledTaskInfo.md
  docset/windows/scheduledtasks/Register-ScheduledTask.md
  docset/windows/scheduledtasks/Set-ScheduledTask.md
  docset/windows/scheduledtasks/Start-ScheduledTask.md
  docset/windows/scheduledtasks/Stop-ScheduledTask.md
  docset/windows/scheduledtasks/Unregister-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Disable-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Enable-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Export-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Get-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Get-ScheduledTaskInfo.md
  docset/winserver2012-ps/scheduledtasks/Register-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Set-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Start-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Stop-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Unregister-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Disable-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Enable-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Export-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Get-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Get-ScheduledTaskInfo.md
  docset/winserver2012r2-ps/scheduledtasks/Register-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Set-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Start-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Stop-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Unregister-ScheduledTask.md
Labels: In review, Sign off

#2092 Publish 8/18/2020 10:30 AM PT
  docset/windows/addsadministration/New-ADComputer.md
  docset/windows/addsadministration/New-ADServiceAccount.md
  docset/windows/addsadministration/New-ADUser.md
  docset/windows/addsadministration/Remove-ADUser.md
  docset/windows/addsadministration/Set-ADComputer.md
  docset/windows/addsadministration/Set-ADServiceAccount.md
  docset/windows/addsadministration/Set-ADUser.md
  docset/windows/scheduledtasks/Disable-ScheduledTask.md
  docset/windows/scheduledtasks/Enable-ScheduledTask.md
  docset/windows/scheduledtasks/Export-ScheduledTask.md
  docset/windows/scheduledtasks/Get-ScheduledTask.md
  docset/windows/scheduledtasks/Get-ScheduledTaskInfo.md
  docset/windows/scheduledtasks/Register-ScheduledTask.md
  docset/windows/scheduledtasks/Set-ScheduledTask.md
  docset/windows/scheduledtasks/Start-ScheduledTask.md
  docset/windows/scheduledtasks/Stop-ScheduledTask.md
  docset/windows/scheduledtasks/Unregister-ScheduledTask.md
  docset/windows/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2012-ps/activedirectory/New-ADComputer.md
  docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md
  docset/winserver2012-ps/activedirectory/New-ADUser.md
  docset/winserver2012-ps/activedirectory/Remove-ADUser.md
  docset/winserver2012-ps/activedirectory/Set-ADComputer.md
  docset/winserver2012-ps/activedirectory/Set-ADServiceAccount.md
  docset/winserver2012-ps/activedirectory/Set-ADUser.md
  docset/winserver2012-ps/scheduledtasks/Disable-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Enable-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Export-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Get-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Get-ScheduledTaskInfo.md
  docset/winserver2012-ps/scheduledtasks/Register-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Set-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Start-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Stop-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Unregister-ScheduledTask.md
  docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2012r2-ps/addsadministration/New-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md
  docset/winserver2012r2-ps/addsadministration/New-ADUser.md
  docset/winserver2012r2-ps/addsadministration/Remove-ADUser.md
  docset/winserver2012r2-ps/addsadministration/Set-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/Set-ADServiceAccount.md
  docset/winserver2012r2-ps/addsadministration/Set-ADUser.md
  docset/winserver2012r2-ps/scheduledtasks/Disable-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Enable-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Export-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Get-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Get-ScheduledTaskInfo.md
  docset/winserver2012r2-ps/scheduledtasks/Register-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Set-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Start-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Stop-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Unregister-ScheduledTask.md
  docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md
Labels: Microsoft submitter

#2060 Fix Get-NetFirewallPortFilter port filter example
  docset/windows/netsecurity/Get-NetFirewallPortFilter.md
Labels: In review, Sign off

#2097 Publish 8/24/2020 10:30 AM PT
  docset/windows/netsecurity/Get-NetFirewallPortFilter.md
Labels: Microsoft submitter

#2095 Added missing ymal info in cmdlets in Microsoft.Windows.ServerManager.Migration
  docset/windows/Microsoft.Windows.ServerManager.Migration/Export-SmigServerSetting.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Get-SmigServerFeature.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Import-SmigServerSetting.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Microsoft.Windows.ServerManager.Migration.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Receive-SmigServerData.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Send-SmigServerData.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/ServerManager.md
Labels: In review, Microsoft submitter, Sign off

#2094 Updated cmdlets under SystemInsights to conform PlatyPS schema
  docset/windows/systeminsights/Add-InsightsCapability.md
  docset/windows/systeminsights/Disable-InsightsCapability.md
  docset/windows/systeminsights/Disable-InsightsCapabilitySchedule.md
  docset/windows/systeminsights/Enable-InsightsCapability.md
  docset/windows/systeminsights/Enable-InsightsCapabilitySchedule.md
  docset/windows/systeminsights/Get-InsightsCapability.md
  docset/windows/systeminsights/Get-InsightsCapabilityAction.md
  docset/windows/systeminsights/Get-InsightsCapabilityResult.md
  docset/windows/systeminsights/Get-InsightsCapabilitySchedule.md
  docset/windows/systeminsights/Invoke-InsightsCapability.md
  docset/windows/systeminsights/Remove-InsightsCapability.md
  docset/windows/systeminsights/Remove-InsightsCapabilityAction.md
  docset/windows/systeminsights/Set-InsightsCapabilityAction.md
  docset/windows/systeminsights/Set-InsightsCapabilitySchedule.md
  docset/windows/systeminsights/SystemInsights.md
  docset/windows/systeminsights/Update-InsightsCapability.md
Labels: In review, Microsoft submitter, Sign off

#2096 Updated mismatched ymal title and header in cmdlet in StorageSubsystem
  docset/windows/storage/Get-StorageSubSystem.md
  docset/windows/storage/Set-StorageSubSystem.md
  docset/winserver2012r2-ps/storage/Get-StorageSubSystem.md
  docset/winserver2012r2-ps/storage/Set-StorageSubSystem.md
Labels: In review, Microsoft submitter, Sign off

#2098 Publish 08/24/2020 3:54 PM
  docset/windows/Microsoft.Windows.ServerManager.Migration/Export-SmigServerSetting.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Get-SmigServerFeature.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Import-SmigServerSetting.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Microsoft.Windows.ServerManager.Migration.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Receive-SmigServerData.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/Send-SmigServerData.md
  docset/windows/Microsoft.Windows.ServerManager.Migration/ServerManager.md
  docset/windows/storage/Get-StorageSubSystem.md
  docset/windows/storage/Set-StorageSubSystem.md
  docset/windows/systeminsights/Add-InsightsCapability.md
  docset/windows/systeminsights/Disable-InsightsCapability.md
  docset/windows/systeminsights/Disable-InsightsCapabilitySchedule.md
  docset/windows/systeminsights/Enable-InsightsCapability.md
  docset/windows/systeminsights/Enable-InsightsCapabilitySchedule.md
  docset/windows/systeminsights/Get-InsightsCapability.md
  docset/windows/systeminsights/Get-InsightsCapabilityAction.md
  docset/windows/systeminsights/Get-InsightsCapabilityResult.md
  docset/windows/systeminsights/Get-InsightsCapabilitySchedule.md
  docset/windows/systeminsights/Invoke-InsightsCapability.md
  docset/windows/systeminsights/Remove-InsightsCapability.md
  docset/windows/systeminsights/Remove-InsightsCapabilityAction.md
  docset/windows/systeminsights/Set-InsightsCapabilityAction.md
  docset/windows/systeminsights/Set-InsightsCapabilitySchedule.md
  docset/windows/systeminsights/SystemInsights.md
  docset/windows/systeminsights/Update-InsightsCapability.md
  docset/winserver2012r2-ps/storage/Get-StorageSubSystem.md
  docset/winserver2012r2-ps/storage/Set-StorageSubSystem.md
Labels: Microsoft submitter
