Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-07, with the labels that each got.

#2019 Resolves #2003
  docset/windows/hyper-v/Set-VMReplicationServer.md
  docset/winserver2012-ps/hyper-v/Set-VMReplicationServer.md
  docset/winserver2012r2-ps/hyper-v/Set-VMReplicationServer.md
Labels: Sign off

#2021 Resolves #2001
  docset/windows/addsadministration/New-ADReplicationSite.md
  docset/winserver2012-ps/activedirectory/New-ADReplicationSite.md
  docset/winserver2012r2-ps/addsadministration/New-ADReplicationSite.md
Labels: In review, Sign off

#2040 Publish 07/01/2020 3:35 PM
  docset/windows/addsadministration/New-ADReplicationSite.md
  docset/windows/hyper-v/Set-VMReplicationServer.md
  docset/winserver2012-ps/activedirectory/New-ADReplicationSite.md
  docset/winserver2012-ps/hyper-v/Set-VMReplicationServer.md
  docset/winserver2012r2-ps/addsadministration/New-ADReplicationSite.md
  docset/winserver2012r2-ps/hyper-v/Set-VMReplicationServer.md
Labels: Microsoft submitter

#2039 Corrected faulty example on doc for Enable-PnpDevice
  docset/windows/pnpdevice/Enable-PnpDevice.md
Labels: In review, Microsoft submitter, Sign off

#2041 Publish 7/2/2020 10:30 AM PT
  docset/windows/pnpdevice/Enable-PnpDevice.md
Labels: Microsoft submitter

#2037 Update Set-MpPreference.md
  docset/windows/defender/Set-MpPreference.md
Labels: In review, Microsoft submitter, Sign off

#2044 Publishing 07/06/2020 3:35 PM
  docset/windows/defender/Set-MpPreference.md
Labels: Microsoft submitter

#2050 Update Remove-DnsServerResourceRecord.md
  docset/windows/dnsserver/Remove-DnsServerResourceRecord.md
  docset/winserver2012-ps/dnsserver/Remove-DnsServerResourceRecord.md
  docset/winserver2012r2-ps/dnsserver/Remove-DnsServerResourceRecord.md
Labels: In review, Sign off

#2054 Publish 07/16/2020 3:32 PM
  docset/windows/dnsserver/Remove-DnsServerResourceRecord.md
  docset/winserver2012-ps/dnsserver/Remove-DnsServerResourceRecord.md
  docset/winserver2012r2-ps/dnsserver/Remove-DnsServerResourceRecord.md
Labels: Microsoft submitter

#2057 Update .gitignore
  .gitignore
  .vscode/extensions.json
Labels: Microsoft submitter

#2058 Publish 07/24/2020 3:30 PM
  .gitignore
  .vscode/extensions.json
Labels: Microsoft submitter

#2049 Update New-ADUser.md
  docset/windows/addsadministration/New-ADComputer.md
  docset/windows/addsadministration/New-ADUser.md
  docset/winserver2012-ps/activedirectory/New-ADComputer.md
  docset/winserver2012-ps/activedirectory/New-ADUser.md
  docset/winserver2012r2-ps/addsadministration/New-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/New-ADUser.md
Labels: In review, Sign off

#2067 Publish 7/31/2020 10:30 AM PT
  docset/windows/addsadministration/New-ADComputer.md
  docset/windows/addsadministration/New-ADUser.md
  docset/winserver2012-ps/activedirectory/New-ADComputer.md
  docset/winserver2012-ps/activedirectory/New-ADUser.md
  docset/winserver2012r2-ps/addsadministration/New-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/New-ADUser.md
Labels: Microsoft submitter
