Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-12, with the labels that each got.

#2189 added requirement
  docset/windows/dnsserver/Add-DnsServerResourceRecordCName.md
Labels: In review, Sign off

#2233 Publish 12/3/2020 10:30 AM PT
  docset/windows/dnsserver/Add-DnsServerResourceRecordCName.md
Labels: Microsoft submitter

#2232 Enable PR preview
  .openpublishing.publish.config.json
Labels: Microsoft submitter

#2234 Enable content preview
  .openpublishing.publish.config.json
Labels: Microsoft submitter

#2218 Resolves #1289
  docset/windows/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md
Labels: In review, Sign off

#2214 revert changes
  docset/windows/failoverclusters/Set-ClusterLog.md
Labels: In review, Sign off

#2197 added several examples
  docset/windows/hyper-v/New-VM.md
  docset/winserver2012-ps/hyper-v/New-VM.md
  docset/winserver2012r2-ps/hyper-v/New-VM.md
Labels: In review, Sign off

#2181 Update protocol description
  docset/windows/netsecurity/New-NetFirewallRule.md
  docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md
  docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md
Labels: In review, Sign off

#2180 Update note section
  docset/windows/nettcpip/Set-NetTCPSetting.md
Labels: In review, Sign off

#2171 removed incorrect note
  docset/windows/dnsclient/Resolve-DnsName.md
  docset/winserver2012r2-ps/dnsclient/Resolve-DnsName.md
Labels: In review, Sign off

#2236 Publish 12/9/2020 10:30 AM PT
  docset/windows/dnsclient/Resolve-DnsName.md
  docset/windows/failoverclusters/Set-ClusterLog.md
  docset/windows/hyper-v/New-VM.md
  docset/windows/netsecurity/New-NetFirewallRule.md
  docset/windows/nettcpip/Set-NetTCPSetting.md
  docset/windows/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2012-ps/hyper-v/New-VM.md
  docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md
  docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2012r2-ps/dnsclient/Resolve-DnsName.md
  docset/winserver2012r2-ps/hyper-v/New-VM.md
  docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md
  docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md
Labels: Microsoft submitter

#2191 Update Set-RDSessionHost.md
  docset/windows/remotedesktop/Set-RDSessionHost.md
Labels: In review, Sign off

#2182 Update Set-VMHost: accurate info on default folders
  docset/windows/hyper-v/Set-VMHost.md
  docset/winserver2012-ps/hyper-v/Set-VMHost.md
  docset/winserver2012r2-ps/hyper-v/Set-VMHost.md
Labels: In review, Sign off

#2192 Register-ScheduledTask: Three fixes
  docset/windows/scheduledtasks/Register-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Register-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Register-ScheduledTask.md
Labels: In review, Sign off

#2187 Update set systemlocale docs
  docset/windows/international/Set-WinSystemLocale.md
  docset/winserver2012-ps/internationalcmdlets/Set-WinSystemLocale.md
  docset/winserver2012r2-ps/international/Set-WinSystemLocale.md
Labels: In review, Microsoft submitter, Sign off

#2222 Update Remove-AppxPackage.md
  docset/windows/appx/Remove-AppxPackage.md
Labels: In review, Sign off

#2201 Update Set-VpnConnectionProxy.md
  docset/windows/vpnclient/Set-VpnConnectionProxy.md
Labels: In review, Microsoft submitter, Sign off

#2244 Publish 12/15/2020 10:30 AM PT
  docset/windows/appx/Remove-AppxPackage.md
  docset/windows/hyper-v/Set-VMHost.md
  docset/windows/international/Set-WinSystemLocale.md
  docset/windows/remotedesktop/Set-RDSessionHost.md
  docset/windows/scheduledtasks/Register-ScheduledTask.md
  docset/windows/vpnclient/Set-VpnConnectionProxy.md
  docset/winserver2012-ps/hyper-v/Set-VMHost.md
  docset/winserver2012-ps/internationalcmdlets/Set-WinSystemLocale.md
  docset/winserver2012-ps/scheduledtasks/Register-ScheduledTask.md
  docset/winserver2012r2-ps/hyper-v/Set-VMHost.md
  docset/winserver2012r2-ps/international/Set-WinSystemLocale.md
  docset/winserver2012r2-ps/scheduledtasks/Register-ScheduledTask.md
Labels: Microsoft submitter

#2167 Update Get-NetIPAddress.md
  docset/windows/nettcpip/Get-NetIPAddress.md
Labels: In review, Sign off

#2176 New-RDVirtualDesktopCollection: Clarifies the meaning of VirtualDesktopTemplateStoragePath
  docset/windows/remotedesktop/New-RDVirtualDesktopCollection.md
Labels: Sign off

#2224 -ScanAvgCPULoadFactor
  docset/windows/defender/Set-MpPreference.md
Labels: In review, Sign off

#2246 Publish 12/17/2020, 10:30 AM PT
  docset/windows/defender/Set-MpPreference.md
  docset/windows/nettcpip/Get-NetIPAddress.md
  docset/windows/remotedesktop/New-RDVirtualDesktopCollection.md
Labels: Microsoft submitter

#2241 Resolves #2226
  docset/windows/msmq/Receive-MsmqQueue.md
  docset/winserver2012-ps/msmq/Receive-MsmqQueue.md
  docset/winserver2012r2-ps/msmq/Receive-MsmqQueue.md
Labels: In review, Sign off

#2238 Resolves #2196
  docset/windows/addsadministration/New-ADServiceAccount.md
  docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md
  docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md
Labels: In review, Sign off
