Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-03, with the labels that each got.

#1802 Add reserved storage commands to DISM
  docset/windows/dism/DISM.md
  docset/windows/dism/Get-WindowsReservedStorageState.md
  docset/windows/dism/Set-WindowsReservedStorageState.md
Labels: Microsoft submitter

#1804 Publish 03/03/2020 3:30 PM PST
  docset/windows/dism/DISM.md
  docset/windows/dism/Get-WindowsReservedStorageState.md
  docset/windows/dism/Set-WindowsReservedStorageState.md
Labels: Microsoft submitter

#1782 Resolves #1693
  docset/windows/netadapter/Enable-NetAdapterVmq.md
  docset/winserver2012-ps/netadapter/Enable-NetAdapterVmq.md
  docset/winserver2012r2-ps/netadapter/Enable-NetAdapterVmq.md
Labels: In review, SignOff

#1807 Publish 3/05/2020 3:36 PM PST
  docset/windows/netadapter/Enable-NetAdapterVmq.md
  docset/winserver2012-ps/netadapter/Enable-NetAdapterVmq.md
  docset/winserver2012r2-ps/netadapter/Enable-NetAdapterVmq.md
Labels: Microsoft submitter

#1761 Romaclac msix nonremovableappspolicy
  docset/windows/appx/Appx.md
  docset/windows/appx/Get-NonRemovableAppsPolicy.md
  docset/windows/appx/Set-NonRemovableAppsPolicy.md
Labels: In review, Ready to Merge, SignOff

#1814 Publish 3/11/2020 3:31 PM PST
  docset/windows/appx/Appx.md
  docset/windows/appx/Get-NonRemovableAppsPolicy.md
  docset/windows/appx/Set-NonRemovableAppsPolicy.md
Labels: Microsoft submitter

#1740 Update New-CIPolicyRule.md
  docset/windows/configci/New-CIPolicyRule.md
Labels: In review, SignOff

#1818 Publish 3/13/2020 10:39 AM PST
  docset/windows/configci/New-CIPolicyRule.md
Labels: Microsoft submitter

#1816 replaced the word TMP by TPM, made bold to TPM
  docset/windows/trustedplatformmodule/Enable-TpmAutoProvisioning.md
Labels: In review, SignOff

#1834 Publish 3/19/2020 3:36 PM PST
  docset/windows/trustedplatformmodule/Enable-TpmAutoProvisioning.md
Labels: Microsoft submitter

#1821 modify cmdlet
  docset/winserver2012-ps/msmq/Receive-MsmqQueue.md
Labels: In review, SignOff

#1828 add details
  docset/windows/international/Get-WinUILanguageOverride.md
Labels: In review, SignOff

#1829 add description
  docset/windows/configci/New-CIPolicy.md
Labels: In review, SignOff

#1825 update what gets scanned
  docset/windows/configci/New-CIPolicy.md
Labels: In review, SignOff

#1787 Fix Ex 2, ClusterName desc, casing
  docset/windows/clusterawareupdating/Invoke-CauRun.md
Labels: In review, Microsoft submitter, SignOff

#1822 add note about missing step
  docset/windows/international/Set-WinUILanguageOverride.md
Labels: In review, SignOff

#1832 Patch 1
  docset/windows/appx/Remove-AppxPackage.md
Labels: In review, SignOff

#1837 Publish 3/20/2020 10:41 AM PST
  docset/windows/appx/Remove-AppxPackage.md
  docset/windows/clusterawareupdating/Invoke-CauRun.md
  docset/windows/configci/New-CIPolicy.md
  docset/windows/international/Get-WinUILanguageOverride.md
  docset/windows/international/Set-WinUILanguageOverride.md
  docset/winserver2012-ps/msmq/Receive-MsmqQueue.md
Labels: Microsoft submitter

#1835 Update Set-SmbServerConfiguration.md
  docset/windows/smbshare/Set-SmbServerConfiguration.md
Labels: In review, SignOff

#1853 Publish 3/24/2020 10:32 AM PST
  docset/windows/smbshare/Set-SmbServerConfiguration.md
Labels: Microsoft submitter

#1823 modify -MounPath value
  docset/windows/startlayout/Import-StartLayout.md
Labels: In review, SignOff

#1859 Publish 3/27/2020 3:38 PM PST
  docset/windows/startlayout/Import-StartLayout.md
Labels: Microsoft submitter

#1820 update rules location
  docset/windows/netsecurity/Get-NetFirewallRule.md
Labels: In review, SignOff

#1836 Update Get-WinUserLanguageList.md
  docset/windows/international/Get-WinUserLanguageList.md
Labels: In review, SignOff

#1861 Publish 3/30/2020 3:35 PM PST
  docset/windows/international/Get-WinUserLanguageList.md
  docset/windows/netsecurity/Get-NetFirewallRule.md
Labels: Microsoft submitter

#1862 Configure public contribution branch
  .openpublishing.publish.config.json
Labels: Microsoft submitter

#1839 inserted hypen between Add and WindowsFeature
  docset/windows/adcsdeployment/Install-AdcsCertificationAuthority.md
Labels: In review, SignOff

#1858 Fixed example 1 New-NetIPAddress.md
  docset/windows/nettcpip/New-NetIPAddress.md
Labels: In review, SignOff

#1860 Fix all instances of broken links for "Cultural Settings"
  docset/windows/international/Get-WinSystemLocale.md
  docset/windows/international/Get-WinUserLanguageList.md
  docset/winserver2012-ps/internationalcmdlets/Get-WinSystemLocale.md
  docset/winserver2012-ps/internationalcmdlets/Get-WinUserLanguageList.md
  docset/winserver2012-ps/internationalcmdlets/New-WinUserLanguageList.md
  docset/winserver2012-ps/internationalcmdlets/Set-Culture.md
  docset/winserver2012-ps/internationalcmdlets/Set-WinSystemLocale.md
  docset/winserver2012-ps/internationalcmdlets/Set-WinUserLanguageList.md
  docset/winserver2012r2-ps/international/Get-WinSystemLocale.md
  docset/winserver2012r2-ps/international/Get-WinUserLanguageList.md
  docset/winserver2012r2-ps/international/New-WinUserLanguageList.md
  docset/winserver2012r2-ps/international/Set-Culture.md
  docset/winserver2012r2-ps/international/Set-WinSystemLocale.md
  docset/winserver2012r2-ps/international/Set-WinUserLanguageList.md
Labels: SignOff

#1863 Publish 3/31/2020 10:42 AM PST
  .openpublishing.publish.config.json
  docset/windows/adcsdeployment/Install-AdcsCertificationAuthority.md
  docset/windows/international/Get-WinSystemLocale.md
  docset/windows/international/Get-WinUserLanguageList.md
  docset/windows/nettcpip/New-NetIPAddress.md
  docset/winserver2012-ps/internationalcmdlets/Get-WinSystemLocale.md
  docset/winserver2012-ps/internationalcmdlets/Get-WinUserLanguageList.md
  docset/winserver2012-ps/internationalcmdlets/New-WinUserLanguageList.md
  docset/winserver2012-ps/internationalcmdlets/Set-Culture.md
  docset/winserver2012-ps/internationalcmdlets/Set-WinSystemLocale.md
  docset/winserver2012-ps/internationalcmdlets/Set-WinUserLanguageList.md
  docset/winserver2012r2-ps/international/Get-WinSystemLocale.md
  docset/winserver2012r2-ps/international/Get-WinUserLanguageList.md
  docset/winserver2012r2-ps/international/New-WinUserLanguageList.md
  docset/winserver2012r2-ps/international/Set-Culture.md
  docset/winserver2012r2-ps/international/Set-WinSystemLocale.md
  docset/winserver2012r2-ps/international/Set-WinUserLanguageList.md
Labels: Microsoft submitter
