Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-09, with the labels that each got.

#2078 Replace legacy build pipeline with PowerShell SDP build pipeline
  .openpublishing.publish.config.json
  docset/docfx.json
  docset/winserver2012r2-ps/hpc/Get-HpcMetricValue.md
  docset/winserver2012r2-ps/hpc/Get-HpcTask.md
Labels: Admin review, Help wanted from PubOps, Microsoft submitter, Sign off, help wanted

#2112 escape html-tag-like content to make content show on published pages
  docset/windows/addsadministration/New-ADComputer.md
  docset/windows/addsadministration/New-ADUser.md
  docset/winserver2012-ps/activedirectory/New-ADComputer.md
  docset/winserver2012-ps/activedirectory/New-ADUser.md
  docset/winserver2012r2-ps/addsadministration/New-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/New-ADUser.md
Labels: Microsoft submitter

#2113 Publish 9/11/2020 10:30 AM PT
  docset/windows/addsadministration/New-ADComputer.md
  docset/windows/addsadministration/New-ADUser.md
  docset/winserver2012-ps/activedirectory/New-ADComputer.md
  docset/winserver2012-ps/activedirectory/New-ADUser.md
  docset/winserver2012r2-ps/addsadministration/New-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/New-ADUser.md
Labels: Microsoft submitter

#2100 Error in example 2 of Get-PrintJob.md
  docset/windows/printmanagement/Get-PrintJob.md
Labels: In review, Sign off

#2115 Update New-Partition.md
  docset/windows/storage/New-Partition.md
Labels: In review, Sign off

#2118 Publish 9/15/20 10:30 AM PDT
  docset/windows/storage/New-Partition.md
Labels: Microsoft submitter

#2119 Remove redirections that have same publish url with other version files
  .openpublishing.redirection.json
Labels: Microsoft submitter

#2127 Publish 09/18/2020, 10:30 AM
  .openpublishing.redirection.json
Labels: Microsoft submitter

#2133 Resolves #2065
  docset/windows/deduplication/Set-DedupVolume.md
  docset/winserver2012-ps/deduplication/Set-DedupVolume.md
  docset/winserver2012r2-ps/deduplication/Set-DedupVolume.md
Labels: In review, Sign off

#2139 Resolves #2108
  docset/windows/dism/Add-WindowsCapability.md
Labels: In review, Sign off

#2134 Resolves #2074
  docset/windows/storage/Enable-PhysicalDiskIdentification.md
Labels: In review, Sign off

#2142 Update docfx.json with new header nav
  docset/docfx.json
Labels: Microsoft submitter

#2143 Publish 9/23/2020 10:30 AM PT
  docset/docfx.json
  docset/windows/deduplication/Set-DedupVolume.md
  docset/windows/dism/Add-WindowsCapability.md
  docset/windows/storage/Enable-PhysicalDiskIdentification.md
  docset/winserver2012-ps/deduplication/Set-DedupVolume.md
  docset/winserver2012r2-ps/deduplication/Set-DedupVolume.md
Labels: Microsoft submitter

#2140 Resovles #2111
  docset/windows/remotedesktop/Remove-RDPersonalVirtualDesktopAssignment.md
  docset/winserver2012-ps/remotedesktop/Remove-RDPersonalVirtualDesktopAssignment.md
  docset/winserver2012r2-ps/remotedesktop/Remove-RDPersonalVirtualDesktopAssignment.md
Labels: In review, Sign off

#2136 Resolves #2064
  docset/windows/adfs/Set-AdfsSslCertificate.md
  docset/winserver2012r2-ps/adfs/Set-AdfsSslCertificate.md
Labels: In review, Sign off

#2135 Resolves #2083
  docset/windows/dfsn/Get-DfsnFolderTarget.md
  docset/winserver2012-ps/dfsn/Get-DfsnFolderTarget.md
  docset/winserver2012r2-ps/dfsn/Get-DfsnFolderTarget.md
Labels: In review, Sign off

#2138 Resolves #2105
  docset/windows/dnsclient/Set-DnsClient.md
  docset/winserver2012-ps/dnsclient/Set-DnsClient.md
  docset/winserver2012r2-ps/dnsclient/Set-DnsClient.md
Labels: In review, Sign off

#2144 Publish 09/23/2020, 3:35 PM
  docset/windows/adfs/Set-AdfsSslCertificate.md
  docset/windows/dfsn/Get-DfsnFolderTarget.md
  docset/windows/dnsclient/Set-DnsClient.md
  docset/windows/remotedesktop/Remove-RDPersonalVirtualDesktopAssignment.md
  docset/winserver2012-ps/dfsn/Get-DfsnFolderTarget.md
  docset/winserver2012-ps/dnsclient/Set-DnsClient.md
  docset/winserver2012-ps/remotedesktop/Remove-RDPersonalVirtualDesktopAssignment.md
  docset/winserver2012r2-ps/adfs/Set-AdfsSslCertificate.md
  docset/winserver2012r2-ps/dfsn/Get-DfsnFolderTarget.md
  docset/winserver2012r2-ps/dnsclient/Set-DnsClient.md
  docset/winserver2012r2-ps/remotedesktop/Remove-RDPersonalVirtualDesktopAssignment.md
Labels: Microsoft submitter

#2148 Update config to enable docfx v3
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  docset/bread/toc.yml
Labels: Microsoft submitter

#2150 Publish 9/25/2020 10:30 AM PT
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  docset/bread/toc.yml
Labels: Admin review, Microsoft submitter

#2122 AppLocker cmdlets only work with GP
  docset/windows/applocker/AppLocker.md
  docset/windows/applocker/Get-AppLockerPolicy.md
  docset/windows/applocker/Set-AppLockerPolicy.md
Labels: Microsoft submitter

#2152 Publish 09/28/2020, 3:33 PM
  docset/windows/applocker/AppLocker.md
  docset/windows/applocker/Get-AppLockerPolicy.md
  docset/windows/applocker/Set-AppLockerPolicy.md
Labels: Microsoft submitter

#2137 Update Get-NetIPConfiguration.md
  docset/winserver2012r2-ps/nettcpip/Get-NetIPConfiguration.md
Labels: In review, Sign off

#2131 Resolves #2075
  docset/windows/addsadministration/New-ADFineGrainedPasswordPolicy.md
  docset/winserver2012-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md
  docset/winserver2012r2-ps/addsadministration/New-ADFineGrainedPasswordPolicy.md
Labels: In review, Sign off

#2129 Resolves #2056
  docset/windows/addsadministration/Get-ADUser.md
  docset/winserver2012-ps/activedirectory/Get-ADUser.md
  docset/winserver2012r2-ps/addsadministration/Get-ADUser.md
Labels: In review, Sign off

#2130 Resolves #2063
  docset/windows/webadministration/New-WebBinding.md
  docset/winserver2012-ps/webadminstration/New-WebBinding.md
  docset/winserver2012r2-ps/webadministration/New-WebBinding.md
Labels: In review, Sign off

#2132 Resolves #2062
  docset/windows/dism/Add-AppxProvisionedPackage.md
  docset/winserver2012-ps/dism/Add-AppxProvisionedPackage.md
  docset/winserver2012r2-ps/dism/Add-AppxProvisionedPackage.md
Labels: In review, Sign off

#2125 Update Get-StorageDiagnosticInfo.md
  docset/windows/storage/Get-StorageDiagnosticInfo.md
Labels: In review, Sign off

#2155 Publish 9/29/2020 3:30 PM PT
  docset/windows/addsadministration/Get-ADUser.md
  docset/windows/addsadministration/New-ADFineGrainedPasswordPolicy.md
  docset/windows/dism/Add-AppxProvisionedPackage.md
  docset/windows/storage/Get-StorageDiagnosticInfo.md
  docset/windows/webadministration/New-WebBinding.md
  docset/winserver2012-ps/activedirectory/Get-ADUser.md
  docset/winserver2012-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md
  docset/winserver2012-ps/dism/Add-AppxProvisionedPackage.md
  docset/winserver2012-ps/webadminstration/New-WebBinding.md
  docset/winserver2012r2-ps/addsadministration/Get-ADUser.md
  docset/winserver2012r2-ps/addsadministration/New-ADFineGrainedPasswordPolicy.md
  docset/winserver2012r2-ps/dism/Add-AppxProvisionedPackage.md
  docset/winserver2012r2-ps/nettcpip/Get-NetIPConfiguration.md
  docset/winserver2012r2-ps/webadministration/New-WebBinding.md
Labels: Microsoft submitter
