Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-10, with the labels that each got.

#2147 Update Set-ADReplicationSite.md
  docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
Labels: In review, Sign off

#2154 Update Get-ADReplicationConnection.md
  docset/windows/addsadministration/Get-ADReplicationConnection.md
  docset/winserver2012-ps/activedirectory/Get-ADReplicationConnection.md
  docset/winserver2012r2-ps/addsadministration/Get-ADReplicationConnection.md
Labels: In review, Sign off

#2146 Update Unregister-ScheduledTask.md
  docset/windows/scheduledtasks/Unregister-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/Unregister-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/Unregister-ScheduledTask.md
Labels: In review, Sign off

#2153 Update Set-ADReplicationSite.md
  docset/windows/addsadministration/Set-ADReplicationSite.md
  docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
  docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md
Labels: In review, Sign off

#2162 Publish 10/5/2020 10:30 AM PT
  docset/windows/addsadministration/Get-ADReplicationConnection.md
  docset/windows/addsadministration/Set-ADReplicationSite.md
  docset/windows/scheduledtasks/Unregister-ScheduledTask.md
  docset/winserver2012-ps/activedirectory/Get-ADReplicationConnection.md
  docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
  docset/winserver2012-ps/scheduledtasks/Unregister-ScheduledTask.md
  docset/winserver2012r2-ps/addsadministration/Get-ADReplicationConnection.md
  docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md
  docset/winserver2012r2-ps/scheduledtasks/Unregister-ScheduledTask.md
Labels: Microsoft submitter

#2158 Update-Set-MpPreference-4519186
  docset/windows/defender/Set-MpPreference.md
Labels: In review, Microsoft submitter, Sign off

#2160 New Parameter DeferRegistrationWhenPackagesAreInUse
  docset/windows/appx/Add-AppxPackage.md
Labels: In review, Microsoft submitter, Sign off

#2165 Publish 10/12/2020 10:30 AM PT
  docset/windows/appx/Add-AppxPackage.md
  docset/windows/defender/Set-MpPreference.md
Labels: Microsoft submitter
