Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-04, with the labels that each got.

#1542 Fix circular redirects
  .openpublishing.redirection.json
Labels: In review, SignOff

#1867 April Fool's Publish 4/1/2020 10:34 AM PST
  .openpublishing.redirection.json
Labels: Microsoft submitter

#1868 Update Debug-VM.md
  docset/windows/hyper-v/Debug-VM.md
Labels: In review, SignOff

#1871 Update Enable-VMMigration.md
  docset/windows/hyper-v/Enable-VMMigration.md
Labels: In review, SignOff

#1872 Update Set-VMProcessor.md
  docset/windows/hyper-v/Set-VMProcessor.md
Labels: In review, SignOff

#1879 Publish 4/3/2020 10:32 AM PST
  docset/windows/hyper-v/Debug-VM.md
  docset/windows/hyper-v/Enable-VMMigration.md
  docset/windows/hyper-v/Set-VMProcessor.md
Labels: Microsoft submitter

#1883 Resolves #1857
  docset/windows/webadministration/Remove-WebGlobalModule.md
  docset/winserver2012-ps/webadminstration/Remove-WebGlobalModule.md
  docset/winserver2012r2-ps/webadministration/Remove-WebGlobalModule.md
Labels: In review, SignOff

#1893 update ICMP
  docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md
Labels: In review, SignOff

#1884 Minor update for FixQuorum option
  docset/windows/failoverclusters/Start-ClusterNode.md
Labels: In review, Microsoft submitter, SignOff

#1895 Publish 4/14/2020 10:40 AM PST
  docset/windows/failoverclusters/Start-ClusterNode.md
  docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md
  docset/windows/webadministration/Remove-WebGlobalModule.md
  docset/winserver2012-ps/webadminstration/Remove-WebGlobalModule.md
  docset/winserver2012r2-ps/webadministration/Remove-WebGlobalModule.md
Labels: Microsoft submitter

#1869 Update Get-ClusterGroup.md
  docset/windows/failoverclusters/Get-ClusterGroup.md
Labels: In review, SignOff

#1870 Update Get-NetTCPConnection.md
  docset/windows/nettcpip/Get-NetTCPConnection.md
  docset/winserver2012r2-ps/nettcpip/Get-NetTCPConnection.md
Labels: In review, SignOff

#1899 Update New-VM.md
  docset/windows/hyper-v/New-VM.md
Labels: In review, SignOff

#1903 Publish 4/20/2020 10:35 AM PST
  docset/windows/failoverclusters/Get-ClusterGroup.md
  docset/windows/hyper-v/New-VM.md
  docset/windows/nettcpip/Get-NetTCPConnection.md
  docset/winserver2012r2-ps/nettcpip/Get-NetTCPConnection.md
Labels: Microsoft submitter

#1902 Add CryptoAlgorithmOption parameter to Export-PfxCertificate cmdlet help
  docset/windows/pkiclient/Export-PfxCertificate.md
Labels: In review, Microsoft submitter, SignOff

#1904 Publish 4/20/2020 3:51 PM PST
  docset/windows/pkiclient/Export-PfxCertificate.md
Labels: Microsoft submitter

#1887 Get-MsmqQueue doesn't work for remote queues, incorrect usage of -Recoverable
  docset/winserver2012-ps/msmq/Send-MsmqQueue.md
Labels: In review, Sign off

#1905 Resolves #1848
  docset/windows/provisioning/Install-ProvisioningPackage.md
Labels: In review, Sign off

#1909 Publish 4/27/2020 10:33 AM PST
  docset/windows/provisioning/Install-ProvisioningPackage.md
  docset/winserver2012-ps/msmq/Send-MsmqQueue.md
Labels: Microsoft submitter

#1917 Add backslash after volume letter
  docset/winserver2012-ps/msonlinebackup/Rename-OBVolume.md
Labels: In review, Microsoft submitter, Sign off

#1918 Publish 4/30/2020 3:37 PM PST
  docset/winserver2012-ps/msonlinebackup/Rename-OBVolume.md
Labels: Microsoft submitter
