Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-06, with the labels that each got.

#1984 Resolves #1939
  docset/windows/scheduledtasks/New-ScheduledTask.md
  docset/winserver2012-ps/scheduledtasks/New-ScheduledTask.md
  docset/winserver2012r2-ps/scheduledtasks/New-ScheduledTask.md
Labels: In review, Sign off

#1983 Resolves #1937
  docset/windows/addsadministration/Get-ADOrganizationalUnit.md
  docset/winserver2012-ps/activedirectory/Get-ADOrganizationalUnit.md
  docset/winserver2012r2-ps/addsadministration/Get-ADOrganizationalUnit.md
Labels: In review, Sign off

#1965 Resolve #1764
  docset/windows/addsadministration/Set-ADUser.md
  docset/winserver2012-ps/activedirectory/Set-ADUser.md
  docset/winserver2012r2-ps/addsadministration/Set-ADUser.md
Labels: In review, Sign off

#1962 Resolves #1841
  docset/windows/addsadministration/Set-ADDefaultDomainPasswordPolicy.md
  docset/winserver2012-ps/activedirectory/Set-ADDefaultDomainPasswordPolicy.md
  docset/winserver2012r2-ps/addsadministration/Set-ADDefaultDomainPasswordPolicy.md
Labels: In review, Sign off

#1964 Resolves #1634
  docset/windows/netadapter/Get-NetAdapter.md
  docset/winserver2012-ps/netadapter/Get-NetAdapter.md
  docset/winserver2012r2-ps/netadapter/Get-NetAdapter.md
Labels: In review, Sign off

#1985 Resolves #1948
  docset/windows/dhcpserver/Get-DhcpServerv4Lease.md
  docset/winserver2012-ps/dhcpserver/Get-DhcpServerv4Lease.md
  docset/winserver2012r2-ps/dhcpserver/Get-DhcpServerv4Lease.md
Labels: In review, Sign off

#2002 Publish 6/1/2020 10:30 AM PT
  docset/windows/addsadministration/Get-ADOrganizationalUnit.md
  docset/windows/addsadministration/Set-ADDefaultDomainPasswordPolicy.md
  docset/windows/addsadministration/Set-ADUser.md
  docset/windows/dhcpserver/Get-DhcpServerv4Lease.md
  docset/windows/netadapter/Get-NetAdapter.md
  docset/windows/scheduledtasks/New-ScheduledTask.md
  docset/winserver2012-ps/activedirectory/Get-ADOrganizationalUnit.md
  docset/winserver2012-ps/activedirectory/Set-ADDefaultDomainPasswordPolicy.md
  docset/winserver2012-ps/activedirectory/Set-ADUser.md
  docset/winserver2012-ps/dhcpserver/Get-DhcpServerv4Lease.md
  docset/winserver2012-ps/netadapter/Get-NetAdapter.md
  docset/winserver2012-ps/scheduledtasks/New-ScheduledTask.md
  docset/winserver2012r2-ps/addsadministration/Get-ADOrganizationalUnit.md
  docset/winserver2012r2-ps/addsadministration/Set-ADDefaultDomainPasswordPolicy.md
  docset/winserver2012r2-ps/addsadministration/Set-ADUser.md
  docset/winserver2012r2-ps/dhcpserver/Get-DhcpServerv4Lease.md
  docset/winserver2012r2-ps/netadapter/Get-NetAdapter.md
  docset/winserver2012r2-ps/scheduledtasks/New-ScheduledTask.md
Labels: Microsoft submitter

#1993 Resolves #1313
  docset/windows/addsadministration/Get-ADComputer.md
  docset/winserver2012-ps/activedirectory/Get-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/Get-ADComputer.md
Labels: In review, Sign off

#1989 Update Set-ADComputer.md
  docset/windows/addsadministration/Set-ADComputer.md
  docset/winserver2012-ps/activedirectory/Set-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/Set-ADComputer.md
Labels: In review, Sign off

#2007 Publish 3:30 PM 06/03/2020
  docset/windows/addsadministration/Get-ADComputer.md
  docset/windows/addsadministration/Set-ADComputer.md
  docset/winserver2012-ps/activedirectory/Get-ADComputer.md
  docset/winserver2012-ps/activedirectory/Set-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/Get-ADComputer.md
  docset/winserver2012r2-ps/addsadministration/Set-ADComputer.md
Labels: Microsoft submitter

#1994 Update Set-WinSystemLocale.md
  docset/winserver2012-ps/internationalcmdlets/Set-WinSystemLocale.md
Labels: In review, Sign off

#1991 Update Set-ProcessMitigation.md
  docset/windows/processmitigations/Set-ProcessMitigation.md
Labels: In review, Sign off

#2010 Publish 6/8/2020 10:30 AM PT
  docset/windows/processmitigations/Set-ProcessMitigation.md
  docset/winserver2012-ps/internationalcmdlets/Set-WinSystemLocale.md
Labels: Microsoft submitter

#1987 Update Set-ADFineGrainedPasswordPolicy.md
  docset/windows/addsadministration/Set-ADFineGrainedPasswordPolicy.md
  docset/winserver2012-ps/activedirectory/Set-ADFineGrainedPasswordPolicy.md
  docset/winserver2012r2-ps/addsadministration/Set-ADFineGrainedPasswordPolicy.md
Labels: In review, Sign off

#1988 Update New-ADFineGrainedPasswordPolicy.md
  docset/windows/addsadministration/New-ADFineGrainedPasswordPolicy.md
  docset/winserver2012-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md
  docset/winserver2012r2-ps/addsadministration/New-ADFineGrainedPasswordPolicy.md
Labels: In review, Sign off

#1992 Update Get-SmbShare.md
  docset/windows/smbshare/Get-SmbShare.md
  docset/winserver2012-ps/smbshare/Get-SmbShare.md
  docset/winserver2012r2-ps/smbshare/Get-SmbShare.md
Labels: In review, Sign off

#1977 Update to include -StubPackageOption
  docset/windows/dism/Add-AppxProvisionedPackage.md
Labels: Microsoft submitter, Sign off

#2013 Publish 6/11/2020 10:30 AM PT
  docset/windows/addsadministration/New-ADFineGrainedPasswordPolicy.md
  docset/windows/addsadministration/Set-ADFineGrainedPasswordPolicy.md
  docset/windows/dism/Add-AppxProvisionedPackage.md
  docset/windows/smbshare/Get-SmbShare.md
  docset/winserver2012-ps/activedirectory/New-ADFineGrainedPasswordPolicy.md
  docset/winserver2012-ps/activedirectory/Set-ADFineGrainedPasswordPolicy.md
  docset/winserver2012-ps/smbshare/Get-SmbShare.md
  docset/winserver2012r2-ps/addsadministration/New-ADFineGrainedPasswordPolicy.md
  docset/winserver2012r2-ps/addsadministration/Set-ADFineGrainedPasswordPolicy.md
  docset/winserver2012r2-ps/smbshare/Get-SmbShare.md
Labels: Microsoft submitter

#2032 Publish 06/26/2020 3:30 PM
  docset/windows/defender/Set-MpPreference.md
Labels: Microsoft submitter

#2020 Resolves #2011
  docset/windows/smbshare/Grant-SmbShareAccess.md
  docset/winserver2012-ps/smbshare/Grant-SmbShareAccess.md
  docset/winserver2012r2-ps/smbshare/Grant-SmbShareAccess.md
Labels: In review, Sign off

#2023 replaced invalid link to new link
  docset/docs-conceptual/mdop/get-started.md
Labels: In review, Sign off

#2030 Extra space in BinaryFilePath parameter example
  docset/windows/configci/ConvertFrom-CIPolicy.md
Labels: In review, Sign off

#2031 Fixed typo in line 80
  docset/windows/trustedplatformmodule/Clear-Tpm.md
Labels: In review, Sign off

#2035 Publish 6/30/2020 10:30 AM PT
  docset/docs-conceptual/mdop/get-started.md
  docset/windows/configci/ConvertFrom-CIPolicy.md
  docset/windows/smbshare/Grant-SmbShareAccess.md
  docset/windows/trustedplatformmodule/Clear-Tpm.md
  docset/winserver2012-ps/smbshare/Grant-SmbShareAccess.md
  docset/winserver2012r2-ps/smbshare/Grant-SmbShareAccess.md
Labels: Microsoft submitter
