Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2020-11, with the labels that each got.

#2170 Resolves #2161
  docset/windows/netconnection/Get-NetConnectionProfile.md
  docset/windows/netconnection/Set-NetConnectionProfile.md
  docset/winserver2012-ps/netconnection/Get-NetConnectionProfile.md
  docset/winserver2012-ps/netconnection/Set-NetConnectionProfile.md
  docset/winserver2012r2-ps/netconnection/Get-NetConnectionProfile.md
  docset/winserver2012r2-ps/netconnection/Set-NetConnectionProfile.md
Labels: In review, Sign off

#2190 Update #2056
  docset/windows/addsadministration/Get-ADUser.md
  docset/winserver2012-ps/activedirectory/Get-ADUser.md
  docset/winserver2012r2-ps/addsadministration/Get-ADUser.md
Labels: Sign off

#2208 chanaged the example
  docset/windows/addsadministration/Set-ADAccountControl.md
Labels: In review, Sign off

#2204 added note about PowerShell 7 compatibility
  docset/windows/addsadministration/ActiveDirectory.md
Labels: In review, Sign off

#2212 chanaged the example
  docset/winserver2012r2-ps/addsadministration/Set-ADAccountControl.md
Labels: In review, Sign off

#2169 Resolves #2157
  docset/windows/dnsserver/Add-DnsServerZoneScope.md
Labels: In review, Sign off

#2213 fixed the example
  docset/windows/fileserverresourcemanager/New-FsrmFileManagementJob.md
  docset/winserver2012-ps/fileserverresourcemanager/New-FsrmFileManagementJob.md
  docset/winserver2012r2-ps/fileserverresourcemanager/New-FsrmFileManagementJob.md
Labels: In review, Sign off

#2215 Publish 11/17/2020, 3:30 PM
  docset/windows/addsadministration/ActiveDirectory.md
  docset/windows/addsadministration/Get-ADUser.md
  docset/windows/addsadministration/Set-ADAccountControl.md
  docset/windows/dnsserver/Add-DnsServerZoneScope.md
  docset/windows/fileserverresourcemanager/New-FsrmFileManagementJob.md
  docset/windows/netconnection/Get-NetConnectionProfile.md
  docset/windows/netconnection/Set-NetConnectionProfile.md
  docset/winserver2012-ps/activedirectory/Get-ADUser.md
  docset/winserver2012-ps/fileserverresourcemanager/New-FsrmFileManagementJob.md
  docset/winserver2012-ps/netconnection/Get-NetConnectionProfile.md
  docset/winserver2012-ps/netconnection/Set-NetConnectionProfile.md
  docset/winserver2012r2-ps/addsadministration/Get-ADUser.md
  docset/winserver2012r2-ps/addsadministration/Set-ADAccountControl.md
  docset/winserver2012r2-ps/fileserverresourcemanager/New-FsrmFileManagementJob.md
  docset/winserver2012r2-ps/netconnection/Get-NetConnectionProfile.md
  docset/winserver2012r2-ps/netconnection/Set-NetConnectionProfile.md
Labels: Microsoft submitter

#2211 added note about elevation
  docset/winserver2012r2-ps/addsadministration/Install-ADServiceAccount.md
Labels: In review, Sign off

#2219 Publish 11/18/2020, 10:30 AM PST
  docset/winserver2012r2-ps/addsadministration/Install-ADServiceAccount.md
Labels: Microsoft submitter

#2209 Resolves #1950
  docset/windows/msmq/Set-MsmqQueueACL.md
  docset/winserver2012-ps/msmq/Set-MsmqQueueACL.md
  docset/winserver2012r2-ps/msmq/Set-MsmqQueueACL.md
Labels: Sign off

#2220 Publish 11/18/2020, 3:30 PM
  docset/windows/msmq/Set-MsmqQueueACL.md
  docset/winserver2012-ps/msmq/Set-MsmqQueueACL.md
  docset/winserver2012r2-ps/msmq/Set-MsmqQueueACL.md
Labels: Microsoft submitter

#2205 Resolves #2053
  docset/windows/failoverclusters/New-Cluster.md
  docset/winserver2012-ps/failoverclusters/New-Cluster.md
  docset/winserver2012r2-ps/failoverclusters/New-Cluster.md
Labels: In review, Sign off

#2217 Resolves #1796
  docset/windows/storage/New-Partition.md
  docset/winserver2012-ps/storage/New-Partition.md
  docset/winserver2012r2-ps/storage/New-Partition.md
Labels: In review, Sign off

#2206 Resolves #2025
  docset/windows/printmanagement/Add-Printer.md
  docset/winserver2012-ps/printmanagement/Add-Printer.md
  docset/winserver2012r2-ps/printmanagement/Add-Printer.md
Labels: In review, Sign off

#2207 Resolves #1812
  docset/windows/webadministration/New-WebAppPool.md
  docset/winserver2012-ps/webadminstration/New-WebAppPool.md
  docset/winserver2012r2-ps/webadministration/New-WebAppPool.md
Labels: In review, Sign off

#2210 Resolves #2024
  docset/windows/hyper-v/Get-VHD.md
  docset/winserver2012-ps/hyper-v/Get-VHD.md
  docset/winserver2012r2-ps/hyper-v/Get-VHD.md
Labels: In review, Sign off

#2172 Update log level description
  docset/windows/dism/Get-WindowsReservedStorageState.md
Labels: In review, Sign off
