Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2021-06, with the labels that each got.

#2483 Wdac ps cmdlet outstanding doc updates
  docset/winserver2022-ps/configci/New-CIPolicy.md
  docset/winserver2022-ps/configci/New-CIPolicyRule.md
  docset/winserver2022-ps/configci/Set-CIPolicyIdInfo.md
Labels: In review, Microsoft submitter, Sign off

#2486 Publish 06/04/2021, 3:30 PM
  docset/winserver2022-ps/configci/New-CIPolicy.md
  docset/winserver2022-ps/configci/New-CIPolicyRule.md
  docset/winserver2022-ps/configci/Set-CIPolicyIdInfo.md
Labels: Microsoft submitter

#2487 Update Set-MpPreference.md
  docset/winserver2019-ps/defender/Set-MpPreference.md
Labels: Microsoft submitter

#2497 Publish 06/08/2021, 3:30 PM
  docset/winserver2019-ps/defender/Set-MpPreference.md
Labels: Microsoft submitter

#2501 Update Set-MpPreference.md
  docset/winserver2019-ps/defender/Set-MpPreference.md
Labels: Microsoft submitter

#2485 Update Get-TlsCipherSuite.md
  docset/winserver2016-ps/tls/Get-TlsCipherSuite.md
  docset/winserver2019-ps/tls/Get-TlsCipherSuite.md
  docset/winserver2022-ps/tls/Get-TlsCipherSuite.md
Labels: In review, Sign off

#2488 Resolves #2436
  docset/mdop/appvclient/add-appvclientconnectiongroup.md
  docset/mdop/appvclient/add-appvclientpackage.md
  docset/mdop/appvclient/add-appvpublishingserver.md
  docset/mdop/appvclient/appvclient.md
  docset/mdop/appvclient/disable-appvclientconnectiongroup.md
  docset/mdop/appvclient/enable-appvclientconnectiongroup.md
  docset/mdop/appvclient/get-appvclientconfiguration.md
  docset/mdop/appvclient/get-appvclientconnectiongroup.md
  docset/mdop/appvclient/get-appvclientmode.md
  docset/mdop/appvclient/get-appvclientpackage.md
  docset/mdop/appvclient/get-appvpublishingserver.md
  docset/mdop/appvclient/get-appvvirtualprocess.md
  docset/mdop/appvclient/mount-appvclientconnectiongroup.md
  docset/mdop/appvclient/mount-appvclientpackage.md
  docset/mdop/appvclient/publish-appvclientpackage.md
  docset/mdop/appvclient/remove-appvclientconnectiongroup.md
  docset/mdop/appvclient/remove-appvclientpackage.md
  docset/mdop/appvclient/remove-appvpublishingserver.md
  docset/mdop/appvclient/repair-appvclientconnectiongroup.md
  docset/mdop/appvclient/repair-appvclientpackage.md
  docset/mdop/appvclient/send-appvclientreport.md
  docset/mdop/appvclient/set-appvclientconfiguration.md
  docset/mdop/appvclient/set-appvclientmode.md
  docset/mdop/appvclient/set-appvclientpackage.md
  docset/mdop/appvclient/set-appvpublishingserver.md
  docset/mdop/appvclient/start-appvvirtualprocess.md
  docset/mdop/appvclient/stop-appvclientconnectiongroup.md
  docset/mdop/appvclient/stop-appvclientpackage.md
  docset/mdop/appvclient/sync-appvpublishingserver.md
  docset/mdop/appvclient/unpublish-appvclientpackage.md
Labels: In review, Sign off

#2489 Resolves #2450
  docset/winserver2012-ps/smbshare/New-SmbShare.md
  docset/winserver2012r2-ps/smbshare/New-SmbShare.md
  docset/winserver2016-ps/smbshare/New-SmbShare.md
  docset/winserver2019-ps/smbshare/New-SmbShare.md
  docset/winserver2022-ps/smbshare/New-SmbShare.md
Labels: In review, Sign off

#2505 Publish 06/10/2021, 3:30 PM
  docset/mdop/appvclient/add-appvclientconnectiongroup.md
  docset/mdop/appvclient/add-appvclientpackage.md
  docset/mdop/appvclient/add-appvpublishingserver.md
  docset/mdop/appvclient/appvclient.md
  docset/mdop/appvclient/disable-appvclientconnectiongroup.md
  docset/mdop/appvclient/enable-appvclientconnectiongroup.md
  docset/mdop/appvclient/get-appvclientconfiguration.md
  docset/mdop/appvclient/get-appvclientconnectiongroup.md
  docset/mdop/appvclient/get-appvclientmode.md
  docset/mdop/appvclient/get-appvclientpackage.md
  docset/mdop/appvclient/get-appvpublishingserver.md
  docset/mdop/appvclient/get-appvvirtualprocess.md
  docset/mdop/appvclient/mount-appvclientconnectiongroup.md
  docset/mdop/appvclient/mount-appvclientpackage.md
  docset/mdop/appvclient/publish-appvclientpackage.md
  docset/mdop/appvclient/remove-appvclientconnectiongroup.md
  docset/mdop/appvclient/remove-appvclientpackage.md
  docset/mdop/appvclient/remove-appvpublishingserver.md
  docset/mdop/appvclient/repair-appvclientconnectiongroup.md
  docset/mdop/appvclient/repair-appvclientpackage.md
  docset/mdop/appvclient/send-appvclientreport.md
  docset/mdop/appvclient/set-appvclientconfiguration.md
  docset/mdop/appvclient/set-appvclientmode.md
  docset/mdop/appvclient/set-appvclientpackage.md
  docset/mdop/appvclient/set-appvpublishingserver.md
  docset/mdop/appvclient/start-appvvirtualprocess.md
  docset/mdop/appvclient/stop-appvclientconnectiongroup.md
  docset/mdop/appvclient/stop-appvclientpackage.md
  docset/mdop/appvclient/sync-appvpublishingserver.md
  docset/mdop/appvclient/unpublish-appvclientpackage.md
  docset/winserver2012-ps/smbshare/New-SmbShare.md
  docset/winserver2012r2-ps/smbshare/New-SmbShare.md
  docset/winserver2016-ps/smbshare/New-SmbShare.md
  docset/winserver2016-ps/tls/Get-TlsCipherSuite.md
  docset/winserver2019-ps/smbshare/New-SmbShare.md
  docset/winserver2019-ps/tls/Get-TlsCipherSuite.md
  docset/winserver2022-ps/smbshare/New-SmbShare.md
  docset/winserver2022-ps/tls/Get-TlsCipherSuite.md
Labels: Microsoft submitter

#2517 Update Set-MpPreference.md
  docset/winserver2019-ps/defender/Set-MpPreference.md
Labels: Microsoft submitter

#2518 docset/winserver2019-ps/defender/Set-MpPreference.md
  docset/winserver2019-ps/defender/Set-MpPreference.md
Labels: In review, Microsoft submitter, Sign off

#2498 Set/Get -AppxPackageAutoUpdateSettings PowerShell cmdlets
  docset/winserver2022-ps/appx/Get-AppxPackageAutoUpdateSettings.md
  docset/winserver2022-ps/appx/Set-AppxPackageAutoUpdateSettings.md
Labels: In review, Microsoft submitter, Sign off

#2519 Publish 06/24/2021, 3:30 PM
  docset/winserver2022-ps/appx/Get-AppxPackageAutoUpdateSettings.md
  docset/winserver2022-ps/appx/Set-AppxPackageAutoUpdateSettings.md
Labels: Microsoft submitter

#2492 Resolves #2446
  docset/winserver2012r2-ps/activedirectory/Get-ADDomainController.md
  docset/winserver2016-ps/activedirectory/Get-ADDomainController.md
  docset/winserver2019-ps/activedirectory/Get-ADDomainController.md
  docset/winserver2022-ps/activedirectory/Get-ADDomainController.md
Labels: In review, Sign off

#2494 Resolves #2445
  docset/winserver2012-ps/webadministration/Get-WebBinding.md
  docset/winserver2012r2-ps/webadministration/Get-WebBinding.md
  docset/winserver2016-ps/webadministration/Get-WebBinding.md
  docset/winserver2019-ps/webadministration/Get-WebBinding.md
  docset/winserver2022-ps/webadministration/Get-WebBinding.md
Labels: In review, Sign off

#2495 Resolves #2479
  docset/winserver2012-ps/hyper-v/Add-VMHardDiskDrive.md
  docset/winserver2012r2-ps/hyper-v/Add-VMHardDiskDrive.md
  docset/winserver2016-ps/hyper-v/Add-VMHardDiskDrive.md
  docset/winserver2019-ps/hyper-v/Add-VMHardDiskDrive.md
  docset/winserver2022-ps/hyper-v/Add-VMHardDiskDrive.md
Labels: In review, Sign off

#2521 Publish 06/28/2021, 10:30 AM
  docset/winserver2012-ps/hyper-v/Add-VMHardDiskDrive.md
  docset/winserver2012-ps/webadministration/Get-WebBinding.md
  docset/winserver2012r2-ps/activedirectory/Get-ADDomainController.md
  docset/winserver2012r2-ps/hyper-v/Add-VMHardDiskDrive.md
  docset/winserver2012r2-ps/webadministration/Get-WebBinding.md
  docset/winserver2016-ps/activedirectory/Get-ADDomainController.md
  docset/winserver2016-ps/hyper-v/Add-VMHardDiskDrive.md
  docset/winserver2016-ps/webadministration/Get-WebBinding.md
  docset/winserver2019-ps/activedirectory/Get-ADDomainController.md
  docset/winserver2019-ps/hyper-v/Add-VMHardDiskDrive.md
  docset/winserver2019-ps/webadministration/Get-WebBinding.md
  docset/winserver2022-ps/activedirectory/Get-ADDomainController.md
  docset/winserver2022-ps/hyper-v/Add-VMHardDiskDrive.md
  docset/winserver2022-ps/webadministration/Get-WebBinding.md
Labels: Microsoft submitter
