Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2021-07, with the labels that each got.

#2496 Update 2022 ActiveDirectory
  docset/winserver2022-ps/activedirectory/Add-ADDomainControllerPasswordReplicationPolicy.md
  docset/winserver2022-ps/activedirectory/Add-ADGroupMember.md
  docset/winserver2022-ps/activedirectory/Get-ADDomainControllerPasswordReplicationPolicyUsage.md
  docset/winserver2022-ps/activedirectory/New-ADComputer.md
  docset/winserver2022-ps/activedirectory/New-ADDCCloneConfigFile.md
  docset/winserver2022-ps/activedirectory/New-ADServiceAccount.md
  docset/winserver2022-ps/activedirectory/New-ADUser.md
  docset/winserver2022-ps/activedirectory/Remove-ADGroupMember.md
  docset/winserver2022-ps/activedirectory/Set-ADAccountAuthenticationPolicySilo.md
  docset/winserver2022-ps/activedirectory/Set-ADComputer.md
  docset/winserver2022-ps/activedirectory/Set-ADForest.md
  docset/winserver2022-ps/activedirectory/Set-ADServiceAccount.md
  docset/winserver2022-ps/activedirectory/Set-ADUser.md
Labels: In review, Microsoft submitter, Sign off

#2513 Add parameters to NetTCPIP for WS2022
  docset/winserver2022-ps/nettcpip/Get-NetIPAddress.md
  docset/winserver2022-ps/nettcpip/Get-NetIPv4Protocol.md
  docset/winserver2022-ps/nettcpip/Get-NetIPv6Protocol.md
  docset/winserver2022-ps/nettcpip/Get-NetRoute.md
  docset/winserver2022-ps/nettcpip/Remove-NetRoute.md
  docset/winserver2022-ps/nettcpip/Set-NetIPv4Protocol.md
  docset/winserver2022-ps/nettcpip/Set-NetIPv6Protocol.md
Labels: In review, Microsoft submitter, Sign off

#2525 Publish 07/01/21, 3:30 PM
  docset/winserver2022-ps/activedirectory/Add-ADDomainControllerPasswordReplicationPolicy.md
  docset/winserver2022-ps/activedirectory/Add-ADGroupMember.md
  docset/winserver2022-ps/activedirectory/Get-ADDomainControllerPasswordReplicationPolicyUsage.md
  docset/winserver2022-ps/activedirectory/New-ADComputer.md
  docset/winserver2022-ps/activedirectory/New-ADDCCloneConfigFile.md
  docset/winserver2022-ps/activedirectory/New-ADServiceAccount.md
  docset/winserver2022-ps/activedirectory/New-ADUser.md
  docset/winserver2022-ps/activedirectory/Remove-ADGroupMember.md
  docset/winserver2022-ps/activedirectory/Set-ADAccountAuthenticationPolicySilo.md
  docset/winserver2022-ps/activedirectory/Set-ADComputer.md
  docset/winserver2022-ps/activedirectory/Set-ADForest.md
  docset/winserver2022-ps/activedirectory/Set-ADServiceAccount.md
  docset/winserver2022-ps/activedirectory/Set-ADUser.md
  docset/winserver2022-ps/nettcpip/Get-NetIPAddress.md
  docset/winserver2022-ps/nettcpip/Get-NetIPv4Protocol.md
  docset/winserver2022-ps/nettcpip/Get-NetIPv6Protocol.md
  docset/winserver2022-ps/nettcpip/Get-NetRoute.md
  docset/winserver2022-ps/nettcpip/Remove-NetRoute.md
  docset/winserver2022-ps/nettcpip/Set-NetIPv4Protocol.md
  docset/winserver2022-ps/nettcpip/Set-NetIPv6Protocol.md
Labels: Microsoft submitter

#2522 Modify Export-StartLayout script documentation for Windows 11
  docset/winserver2019-ps/startlayout/Export-StartLayout.md
Labels: In review, Sign off

#2536 Publish 07/08/2021, 10:30 AM
  docset/winserver2019-ps/startlayout/Export-StartLayout.md
Labels: Microsoft submitter

#2508 Added the location of the export zone file
  docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md
Labels: In review, Sign off

#2520 Resolves #2423
  docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md
  docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md
  docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md
  docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md
  docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md
Labels: In review, Sign off

#2552 Publish 07/19/2021, 10:30 AM
  docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md
  docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md
  docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md
  docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md
  docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md
  docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md
Labels: Microsoft submitter

#2553 Remove Hyper-V from CabGen exclusions
  docset/mapping/cabgenConfig.json
Labels: Microsoft submitter

#2554 Publish 07/19/2021, 3:30 PM
  docset/mapping/cabgenConfig.json
Labels: Microsoft submitter

#2569 Publish 07/29/2021, 3:30 PM
  docset/winserver2012-ps/international/Get-WinLanguageBarOption.md
  docset/winserver2012-ps/iscsi/Update-IscsiTargetPortal.md
  docset/winserver2012-ps/netqos/New-NetQosPolicy.md
  docset/winserver2012r2-ps/international/Get-WinLanguageBarOption.md
  docset/winserver2012r2-ps/iscsi/Update-IscsiTargetPortal.md
  docset/winserver2012r2-ps/netqos/New-NetQosPolicy.md
  docset/winserver2016-ps/international/Get-WinLanguageBarOption.md
  docset/winserver2016-ps/iscsi/Update-IscsiTargetPortal.md
  docset/winserver2016-ps/netqos/New-NetQosPolicy.md
  docset/winserver2019-ps/international/Get-WinLanguageBarOption.md
  docset/winserver2019-ps/iscsi/Update-IscsiTargetPortal.md
  docset/winserver2019-ps/netqos/New-NetQosPolicy.md
  docset/winserver2022-ps/international/Get-WinLanguageBarOption.md
  docset/winserver2022-ps/iscsi/Update-IscsiTargetPortal.md
  docset/winserver2022-ps/netqos/New-NetQosPolicy.md
Labels: Microsoft submitter
