Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2021-09, with the labels that each got.

#2609 fix wrong syntax
  docset/winserver2019-ps/printmanagement/Set-PrintConfiguration.md
Labels: Sign off, In review

#2631 Update Export-StartLayout.md
  docset/winserver2019-ps/startlayout/Export-StartLayout.md
Labels: Sign off, In review

#2638 Publish 09/07/2021, 10:30 AM
  docset/winserver2019-ps/printmanagement/Set-PrintConfiguration.md
  docset/winserver2019-ps/startlayout/Export-StartLayout.md
Labels: Microsoft submitter

#2608 WindowsUpdate PowerShell reference update
  docset/winserver2022-ps/windowsupdate/Get-WindowsUpdateLog.md
Labels: Microsoft submitter

#2607 dfsn PowerShell reference update
  docset/winserver2022-ps/dfsn/Get-DfsnAccess.md
  docset/winserver2022-ps/dfsn/Get-DfsnFolder.md
  docset/winserver2022-ps/dfsn/Get-DfsnFolderTarget.md
  docset/winserver2022-ps/dfsn/Get-DfsnRoot.md
  docset/winserver2022-ps/dfsn/Get-DfsnRootTarget.md
  docset/winserver2022-ps/dfsn/Get-DfsnServerConfiguration.md
  docset/winserver2022-ps/dfsn/Grant-DfsnAccess.md
  docset/winserver2022-ps/dfsn/Move-DfsnFolder.md
  docset/winserver2022-ps/dfsn/New-DfsnFolder.md
  docset/winserver2022-ps/dfsn/New-DfsnFolderTarget.md
  docset/winserver2022-ps/dfsn/New-DfsnRoot.md
  docset/winserver2022-ps/dfsn/New-DfsnRootTarget.md
  docset/winserver2022-ps/dfsn/Remove-DfsnAccess.md
  docset/winserver2022-ps/dfsn/Remove-DfsnFolder.md
  docset/winserver2022-ps/dfsn/Remove-DfsnFolderTarget.md
  docset/winserver2022-ps/dfsn/Remove-DfsnRoot.md
  docset/winserver2022-ps/dfsn/Remove-DfsnRootTarget.md
  docset/winserver2022-ps/dfsn/Revoke-DfsnAccess.md
  docset/winserver2022-ps/dfsn/Set-DfsnFolder.md
  docset/winserver2022-ps/dfsn/Set-DfsnFolderTarget.md
  docset/winserver2022-ps/dfsn/Set-DfsnRoot.md
  docset/winserver2022-ps/dfsn/Set-DfsnRootTarget.md
  docset/winserver2022-ps/dfsn/Set-DfsnServerConfiguration.md
Labels: Microsoft submitter

#2606 tls PowerShell reference update
  docset/winserver2022-ps/tls/Disable-TlsEccCurve.md
  docset/winserver2022-ps/tls/Enable-TlsEccCurve.md
  docset/winserver2022-ps/tls/Get-TlsEccCurve.md
Labels: Microsoft submitter

#2644 Publish 09/08/2021, 10:30 AM
  docset/winserver2022-ps/dfsn/Get-DfsnAccess.md
  docset/winserver2022-ps/dfsn/Get-DfsnFolder.md
  docset/winserver2022-ps/dfsn/Get-DfsnFolderTarget.md
  docset/winserver2022-ps/dfsn/Get-DfsnRoot.md
  docset/winserver2022-ps/dfsn/Get-DfsnRootTarget.md
  docset/winserver2022-ps/dfsn/Get-DfsnServerConfiguration.md
  docset/winserver2022-ps/dfsn/Grant-DfsnAccess.md
  docset/winserver2022-ps/dfsn/Move-DfsnFolder.md
  docset/winserver2022-ps/dfsn/New-DfsnFolder.md
  docset/winserver2022-ps/dfsn/New-DfsnFolderTarget.md
  docset/winserver2022-ps/dfsn/New-DfsnRoot.md
  docset/winserver2022-ps/dfsn/New-DfsnRootTarget.md
  docset/winserver2022-ps/dfsn/Remove-DfsnAccess.md
  docset/winserver2022-ps/dfsn/Remove-DfsnFolder.md
  docset/winserver2022-ps/dfsn/Remove-DfsnFolderTarget.md
  docset/winserver2022-ps/dfsn/Remove-DfsnRoot.md
  docset/winserver2022-ps/dfsn/Remove-DfsnRootTarget.md
  docset/winserver2022-ps/dfsn/Revoke-DfsnAccess.md
  docset/winserver2022-ps/dfsn/Set-DfsnFolder.md
  docset/winserver2022-ps/dfsn/Set-DfsnFolderTarget.md
  docset/winserver2022-ps/dfsn/Set-DfsnRoot.md
  docset/winserver2022-ps/dfsn/Set-DfsnRootTarget.md
  docset/winserver2022-ps/dfsn/Set-DfsnServerConfiguration.md
  docset/winserver2022-ps/tls/Disable-TlsEccCurve.md
  docset/winserver2022-ps/tls/Enable-TlsEccCurve.md
  docset/winserver2022-ps/tls/Get-TlsEccCurve.md
  docset/winserver2022-ps/windowsupdate/Get-WindowsUpdateLog.md
Labels: Microsoft submitter

#2604 DFSR PowerShell reference update
  docset/winserver2022-ps/dfsr/ConvertFrom-DfsrGuid.md
  docset/winserver2022-ps/dfsr/Get-DfsReplicatedFolder.md
  docset/winserver2022-ps/dfsr/Get-DfsReplicationGroup.md
  docset/winserver2022-ps/dfsr/Get-DfsrBacklog.md
  docset/winserver2022-ps/dfsr/Get-DfsrConnection.md
  docset/winserver2022-ps/dfsr/Get-DfsrConnectionSchedule.md
  docset/winserver2022-ps/dfsr/Get-DfsrDelegation.md
  docset/winserver2022-ps/dfsr/Get-DfsrGroupSchedule.md
  docset/winserver2022-ps/dfsr/Get-DfsrIdRecord.md
  docset/winserver2022-ps/dfsr/Get-DfsrMember.md
  docset/winserver2022-ps/dfsr/Get-DfsrMembership.md
  docset/winserver2022-ps/dfsr/Grant-DfsrDelegation.md
  docset/winserver2022-ps/dfsr/New-DfsReplicatedFolder.md
  docset/winserver2022-ps/dfsr/Remove-DfsReplicatedFolder.md
  docset/winserver2022-ps/dfsr/Remove-DfsrConnection.md
  docset/winserver2022-ps/dfsr/Remove-DfsrMember.md
  docset/winserver2022-ps/dfsr/Remove-DfsrPropagationTestFile.md
  docset/winserver2022-ps/dfsr/Revoke-DfsrDelegation.md
  docset/winserver2022-ps/dfsr/Set-DfsReplicatedFolder.md
  docset/winserver2022-ps/dfsr/Set-DfsReplicationGroup.md
  docset/winserver2022-ps/dfsr/Set-DfsrConnection.md
  docset/winserver2022-ps/dfsr/Set-DfsrConnectionSchedule.md
  docset/winserver2022-ps/dfsr/Set-DfsrGroupSchedule.md
  docset/winserver2022-ps/dfsr/Set-DfsrMember.md
  docset/winserver2022-ps/dfsr/Set-DfsrMembership.md
  docset/winserver2022-ps/dfsr/Start-DfsrPropagationTest.md
  docset/winserver2022-ps/dfsr/Suspend-DfsReplicationGroup.md
  docset/winserver2022-ps/dfsr/Sync-DfsReplicationGroup.md
  docset/winserver2022-ps/dfsr/Write-DfsrHealthReport.md
  docset/winserver2022-ps/dfsr/Write-DfsrPropagationReport.md
Labels: Microsoft submitter

#2648 Publish 09/09/2021, 10:30 AM
  docset/winserver2022-ps/dfsr/ConvertFrom-DfsrGuid.md
  docset/winserver2022-ps/dfsr/Get-DfsReplicatedFolder.md
  docset/winserver2022-ps/dfsr/Get-DfsReplicationGroup.md
  docset/winserver2022-ps/dfsr/Get-DfsrBacklog.md
  docset/winserver2022-ps/dfsr/Get-DfsrConnection.md
  docset/winserver2022-ps/dfsr/Get-DfsrConnectionSchedule.md
  docset/winserver2022-ps/dfsr/Get-DfsrDelegation.md
  docset/winserver2022-ps/dfsr/Get-DfsrGroupSchedule.md
  docset/winserver2022-ps/dfsr/Get-DfsrIdRecord.md
  docset/winserver2022-ps/dfsr/Get-DfsrMember.md
  docset/winserver2022-ps/dfsr/Get-DfsrMembership.md
  docset/winserver2022-ps/dfsr/Grant-DfsrDelegation.md
  docset/winserver2022-ps/dfsr/New-DfsReplicatedFolder.md
  docset/winserver2022-ps/dfsr/Remove-DfsReplicatedFolder.md
  docset/winserver2022-ps/dfsr/Remove-DfsrConnection.md
  docset/winserver2022-ps/dfsr/Remove-DfsrMember.md
  docset/winserver2022-ps/dfsr/Remove-DfsrPropagationTestFile.md
  docset/winserver2022-ps/dfsr/Revoke-DfsrDelegation.md
  docset/winserver2022-ps/dfsr/Set-DfsReplicatedFolder.md
  docset/winserver2022-ps/dfsr/Set-DfsReplicationGroup.md
  docset/winserver2022-ps/dfsr/Set-DfsrConnection.md
  docset/winserver2022-ps/dfsr/Set-DfsrConnectionSchedule.md
  docset/winserver2022-ps/dfsr/Set-DfsrGroupSchedule.md
  docset/winserver2022-ps/dfsr/Set-DfsrMember.md
  docset/winserver2022-ps/dfsr/Set-DfsrMembership.md
  docset/winserver2022-ps/dfsr/Start-DfsrPropagationTest.md
  docset/winserver2022-ps/dfsr/Suspend-DfsReplicationGroup.md
  docset/winserver2022-ps/dfsr/Sync-DfsReplicationGroup.md
  docset/winserver2022-ps/dfsr/Write-DfsrHealthReport.md
  docset/winserver2022-ps/dfsr/Write-DfsrPropagationReport.md
Labels: Microsoft submitter

#2593 DnsClient PowerShell reference update
  docset/winserver2022-ps/dnsclient/Add-DnsClientDohServerAddress.md
  docset/winserver2022-ps/dnsclient/DnsClient.md
  docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md
  docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md
  docset/winserver2022-ps/dnsclient/Set-DnsClientDohServerAddress.md
Labels: Microsoft submitter

#2652 Publish 09/10/2021, 3:30 PM
  docset/winserver2022-ps/dnsclient/Add-DnsClientDohServerAddress.md
  docset/winserver2022-ps/dnsclient/DnsClient.md
  docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md
  docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md
  docset/winserver2022-ps/dnsclient/Set-DnsClientDohServerAddress.md
Labels: Microsoft submitter

#2634 Resolve #2546
  docset/winserver2012r2-ps/dhcpserver/Add-DhcpServerv4Reservation.md
  docset/winserver2016-ps/dhcpserver/Add-DhcpServerv4Reservation.md
  docset/winserver2019-ps/dhcpserver/Add-DhcpServerv4Reservation.md
  docset/winserver2022-ps/dhcpserver/Add-DhcpServerv4Reservation.md
Labels: Sign off, In review

#2632 Resolves #2533
  docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md
  docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md
  docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md
  docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md
  docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md
Labels: Sign off, In review

#2653 Publish 09/13/2021, 10:30 AM
  docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md
  docset/winserver2012r2-ps/dhcpserver/Add-DhcpServerv4Reservation.md
  docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md
  docset/winserver2016-ps/dhcpserver/Add-DhcpServerv4Reservation.md
  docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md
  docset/winserver2019-ps/dhcpserver/Add-DhcpServerv4Reservation.md
  docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md
  docset/winserver2022-ps/dhcpserver/Add-DhcpServerv4Reservation.md
  docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md
Labels: Microsoft submitter

#2596 TrustedPlatformModule PowerShell reference update
  docset/winserver2022-ps/trustedplatformmodule/Clear-Tpm.md
Labels: Microsoft submitter

#2654 Publish 09/13/2021, 3:30 PM
  docset/winserver2022-ps/trustedplatformmodule/Clear-Tpm.md
Labels: Microsoft submitter

#2640 Resolves #2590
  docset/winserver2016-ps/dnsserver/Add-DnsServerQueryResolutionPolicy.md
  docset/winserver2019-ps/dnsserver/Add-DnsServerQueryResolutionPolicy.md
  docset/winserver2022-ps/dnsserver/Add-DnsServerQueryResolutionPolicy.md
Labels: Sign off, In review

#2637 Resolves #2573
  docset/winserver2012-ps/webadministration/New-WebBinding.md
  docset/winserver2012r2-ps/webadministration/New-WebBinding.md
  docset/winserver2016-ps/webadministration/New-WebBinding.md
  docset/winserver2019-ps/webadministration/New-WebBinding.md
  docset/winserver2022-ps/webadministration/New-WebBinding.md
Labels: Sign off, In review

#2633 Resolves #2538
  docset/winserver2016-ps/tls/Enable-TlsCipherSuite.md
  docset/winserver2019-ps/tls/Enable-TlsCipherSuite.md
  docset/winserver2022-ps/tls/Enable-TlsCipherSuite.md
Labels: Sign off, In review

#2639 Resolves #2581
  docset/winserver2012r2-ps/activedirectory/Get-ADFineGrainedPasswordPolicy.md
  docset/winserver2016-ps/activedirectory/Get-ADFineGrainedPasswordPolicy.md
  docset/winserver2019-ps/activedirectory/Get-ADFineGrainedPasswordPolicy.md
  docset/winserver2022-ps/activedirectory/Get-ADFineGrainedPasswordPolicy.md
Labels: Sign off, In review

#2629 ADCSDeployment PowerShell reference update
  docset/winserver2022-ps/adcsdeployment/Install-AdcsCertificationAuthority.md
  docset/winserver2022-ps/adcsdeployment/Install-AdcsEnrollmentPolicyWebService.md
  docset/winserver2022-ps/adcsdeployment/Install-AdcsEnrollmentWebService.md
  docset/winserver2022-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.md
  docset/winserver2022-ps/adcsdeployment/Install-AdcsOnlineResponder.md
  docset/winserver2022-ps/adcsdeployment/Install-AdcsWebEnrollment.md
  docset/winserver2022-ps/adcsdeployment/Uninstall-AdcsCertificationAuthority.md
  docset/winserver2022-ps/adcsdeployment/Uninstall-AdcsEnrollmentPolicyWebService.md
  docset/winserver2022-ps/adcsdeployment/Uninstall-AdcsEnrollmentWebService.md
  docset/winserver2022-ps/adcsdeployment/Uninstall-AdcsNetworkDeviceEnrollmentService.md
  docset/winserver2022-ps/adcsdeployment/Uninstall-AdcsOnlineResponder.md
  docset/winserver2022-ps/adcsdeployment/Uninstall-AdcsWebEnrollment.md
Labels: Sign off, In review, Microsoft submitter

#2636 Resolves #2548
  docset/winserver2012r2-ps/adfs/Test-AdfsFarmJoin.md
  docset/winserver2016-ps/adfs/Test-AdfsFarmJoin.md
  docset/winserver2019-ps/adfs/Test-AdfsFarmJoin.md
  docset/winserver2022-ps/adfs/Test-AdfsFarmJoin.md
Labels: Sign off, In review

#2625 MsDtc PowerShell reference update: Update an external help file.
  docset/winserver2022-ps/msdtc/Test-Dtc.md
Labels: Sign off, In review, Microsoft submitter

#2580 Windows Server 2022 Update to Bitlocker PowerShell Module
  docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md
  docset/winserver2022-ps/bitlocker/BitLocker.md
Labels: Sign off, In review, Microsoft submitter

#2622 MSMQ PowerShell reference update
  docset/winserver2022-ps/msmq/Clear-MSMQOutgoingQueue.md
  docset/winserver2022-ps/msmq/Clear-MSMQQueue.md
  docset/winserver2022-ps/msmq/Enable-MSMQCertificate.md
  docset/winserver2022-ps/msmq/Get-MSMQCertificate.md
  docset/winserver2022-ps/msmq/Get-MSMQOutgoingQueue.md
  docset/winserver2022-ps/msmq/Get-MsmqQueue.md
  docset/winserver2022-ps/msmq/Get-MsmqQueueACL.md
  docset/winserver2022-ps/msmq/Get-MsmqQueueManager.md
  docset/winserver2022-ps/msmq/Get-MsmqQueueManagerACL.md
  docset/winserver2022-ps/msmq/Move-MsmqMessage.md
  docset/winserver2022-ps/msmq/New-MsmqMessage.md
  docset/winserver2022-ps/msmq/New-MsmqQueue.md
  docset/winserver2022-ps/msmq/Receive-MsmqQueue.md
  docset/winserver2022-ps/msmq/Remove-MsmqCertificate.md
  docset/winserver2022-ps/msmq/Remove-MsmqQueue.md
  docset/winserver2022-ps/msmq/Resume-MsmqOutgoingQueue.md
  docset/winserver2022-ps/msmq/Send-MsmqQueue.md
  docset/winserver2022-ps/msmq/Set-MsmqQueue.md
  docset/winserver2022-ps/msmq/Set-MsmqQueueACL.md
  docset/winserver2022-ps/msmq/Set-MsmqQueueManager.md
  docset/winserver2022-ps/msmq/Set-MsmqQueueManagerACL.md
  docset/winserver2022-ps/msmq/Suspend-MsmqOutgoingQueue.md
Labels: Sign off, Microsoft submitter

#2603 UpdateServices PowerShell reference update
  docset/winserver2022-ps/updateservices/Add-WsusComputer.md
  docset/winserver2022-ps/updateservices/Add-WsusDynamicCategory.md
  docset/winserver2022-ps/updateservices/Approve-WsusUpdate.md
  docset/winserver2022-ps/updateservices/Deny-WsusUpdate.md
  docset/winserver2022-ps/updateservices/Get-WsusClassification.md
  docset/winserver2022-ps/updateservices/Get-WsusComputer.md
  docset/winserver2022-ps/updateservices/Get-WsusDynamicCategory.md
  docset/winserver2022-ps/updateservices/Get-WsusProduct.md
  docset/winserver2022-ps/updateservices/Get-WsusServer.md
  docset/winserver2022-ps/updateservices/Get-WsusUpdate.md
  docset/winserver2022-ps/updateservices/Remove-WsusDynamicCategory.md
  docset/winserver2022-ps/updateservices/Set-WsusClassification.md
  docset/winserver2022-ps/updateservices/Set-WsusDynamicCategory.md
  docset/winserver2022-ps/updateservices/Set-WsusProduct.md
  docset/winserver2022-ps/updateservices/Set-WsusServerSynchronization.md
Labels: Sign off, Microsoft submitter

#2623 AppLocker PowerShell reference update
  docset/winserver2022-ps/applocker/New-AppLockerPolicy.md
Labels: Sign off, In review, Microsoft submitter

#2624 WebApplicationProxy PowerShell reference update
  docset/winserver2022-ps/webapplicationproxy/Add-WebApplicationProxyApplication.md
  docset/winserver2022-ps/webapplicationproxy/Get-WebApplicationProxyApplication.md
  docset/winserver2022-ps/webapplicationproxy/Get-WebApplicationProxyAvailableADFSRelyingParty.md
  docset/winserver2022-ps/webapplicationproxy/Get-WebApplicationProxyConfiguration.md
  docset/winserver2022-ps/webapplicationproxy/Get-WebApplicationProxyHealth.md
  docset/winserver2022-ps/webapplicationproxy/Get-WebApplicationProxySslCertificate.md
  docset/winserver2022-ps/webapplicationproxy/Install-WebApplicationProxy.md
  docset/winserver2022-ps/webapplicationproxy/Remove-WebApplicationProxyApplication.md
  docset/winserver2022-ps/webapplicationproxy/Set-WebApplicationProxyApplication.md
  docset/winserver2022-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md
  docset/winserver2022-ps/webapplicationproxy/Set-WebApplicationProxySslCertificate.md
  docset/winserver2022-ps/webapplicationproxy/Update-WebApplicationProxyDeviceRegistration.md
Labels: Sign off, Microsoft submitter

#2588 SmbShare PowerShell reference update
  docset/winserver2022-ps/smbshare/Block-SmbShareAccess.md
  docset/winserver2022-ps/smbshare/Close-SmbOpenFile.md
  docset/winserver2022-ps/smbshare/Close-SmbSession.md
  docset/winserver2022-ps/smbshare/Disable-SmbDelegation.md
  docset/winserver2022-ps/smbshare/Enable-SmbDelegation.md
  docset/winserver2022-ps/smbshare/Get-SmbClientConfiguration.md
  docset/winserver2022-ps/smbshare/Get-SmbDelegation.md
  docset/winserver2022-ps/smbshare/Get-SmbGlobalMapping.md
  docset/winserver2022-ps/smbshare/Get-SmbServerCertProps.md
  docset/winserver2022-ps/smbshare/Get-SmbServerCertificateMapping.md
  docset/winserver2022-ps/smbshare/Get-SmbServerConfiguration.md
  docset/winserver2022-ps/smbshare/Get-SmbShare.md
  docset/winserver2022-ps/smbshare/Get-SmbShareAccess.md
  docset/winserver2022-ps/smbshare/Grant-SmbShareAccess.md
  docset/winserver2022-ps/smbshare/New-SmbGlobalMapping.md
  docset/winserver2022-ps/smbshare/New-SmbMapping.md
  docset/winserver2022-ps/smbshare/New-SmbMultichannelConstraint.md
  docset/winserver2022-ps/smbshare/New-SmbServerCertificateMapping.md
  docset/winserver2022-ps/smbshare/New-SmbShare.md
  docset/winserver2022-ps/smbshare/Remove-SmbComponent.md
  docset/winserver2022-ps/smbshare/Remove-SmbGlobalMapping.md
  docset/winserver2022-ps/smbshare/Remove-SmbMapping.md
  docset/winserver2022-ps/smbshare/Remove-SmbMultichannelConstraint.md
  docset/winserver2022-ps/smbshare/Remove-SmbServerCertificateMapping.md
  docset/winserver2022-ps/smbshare/Remove-SmbShare.md
  docset/winserver2022-ps/smbshare/Revoke-SmbShareAccess.md
  docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.md
  docset/winserver2022-ps/smbshare/Set-SmbClientConfiguration.md
  docset/winserver2022-ps/smbshare/Set-SmbPathAcl.md
  docset/winserver2022-ps/smbshare/Set-SmbServerCertificateMapping.md
  docset/winserver2022-ps/smbshare/Set-SmbServerConfiguration.md
  docset/winserver2022-ps/smbshare/Set-SmbShare.md
  docset/winserver2022-ps/smbshare/SmbShare.md
  docset/winserver2022-ps/smbshare/Unblock-SmbShareAccess.md
Labels: Sign off, In review, Microsoft submitter

#2664 Publish 09/17/2021, 3:30 PM
  docset/winserver2019-ps/bitstransfer/Start-BitsTransfer.md
Labels: Microsoft submitter

#2563 Update Appx cmdlets for WS2022
  docset/winserver2022-ps/appx/Add-AppxPackage.md
  docset/winserver2022-ps/appx/Get-NonRemovableAppsPolicy.md
  docset/winserver2022-ps/appx/Remove-AppxPackage.md
  docset/winserver2022-ps/appx/Reset-AppxPackage.md
  docset/winserver2022-ps/appx/Set-NonRemovableAppsPolicy.md
Labels: Back to submitter, Microsoft submitter

#2669 Publish 09/22/21, 3:30 PM
  docset/winserver2022-ps/appx/Add-AppxPackage.md
  docset/winserver2022-ps/appx/Get-NonRemovableAppsPolicy.md
  docset/winserver2022-ps/appx/Remove-AppxPackage.md
  docset/winserver2022-ps/appx/Reset-AppxPackage.md
  docset/winserver2022-ps/appx/Set-NonRemovableAppsPolicy.md
Labels: Microsoft submitter

#2630 ADCSAdministration PowerShell reference update
  docset/winserver2022-ps/adcsadministration/ADCSAdministration.md
  docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md
  docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md
  docset/winserver2022-ps/adcsadministration/Add-CATemplate.md
  docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md
  docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md
  docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md
  docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md
  docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md
  docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md
  docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md
Labels: Microsoft submitter

#2614 StartLayout PowerShell reference update
  docset/winserver2022-ps/startlayout/Export-StartLayout.md
  docset/winserver2022-ps/startlayout/Export-StartLayoutEdgeAssets.md
  docset/winserver2022-ps/startlayout/StartLayout.md
Labels: Microsoft submitter

#2673 Publish 09/23/21, 3:30 PM
  docset/winserver2022-ps/adcsadministration/ADCSAdministration.md
  docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md
  docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md
  docset/winserver2022-ps/adcsadministration/Add-CATemplate.md
  docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md
  docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md
  docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md
  docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md
  docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md
  docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md
  docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md
  docset/winserver2022-ps/startlayout/Export-StartLayout.md
  docset/winserver2022-ps/startlayout/Export-StartLayoutEdgeAssets.md
  docset/winserver2022-ps/startlayout/StartLayout.md
Labels: Microsoft submitter

#2674 Change Uservoice URL to Feedback Hub
  docset/docfx.json
Labels: Microsoft submitter

#2677 Publish 09/24/2021, 10:30 AM
  docset/docfx.json
Labels: Microsoft submitter

#2672 ipamServer PowerShell reference update
  docset/winserver2022-ps/ipamserver/Invoke-IpamGpoProvisioning.md
Labels: Microsoft submitter

#2679 Publish 09/27/2021, 10:30 AM
  docset/winserver2022-ps/ipamserver/Invoke-IpamGpoProvisioning.md
Labels: Microsoft submitter

#2676 IscsiTarget PowerShell reference update
  docset/winserver2022-ps/iscsitarget/Export-IscsiTargetServerConfiguration.md
  docset/winserver2022-ps/iscsitarget/Import-IscsiTargetServerConfiguration.md
Labels: Microsoft submitter

#2675 NetQos PowerShell reference update
  docset/winserver2022-ps/netqos/Get-NetQosPolicy.md
  docset/winserver2022-ps/netqos/New-NetQosPolicy.md
  docset/winserver2022-ps/netqos/Remove-NetQosPolicy.md
  docset/winserver2022-ps/netqos/Set-NetQosPolicy.md
Labels: Microsoft submitter

#2684 NetworkSwitchManager PowerShell reference update
  docset/winserver2022-ps/networkswitchmanager/Disable-NetworkSwitchEthernetPort.md
  docset/winserver2022-ps/networkswitchmanager/Disable-NetworkSwitchFeature.md
  docset/winserver2022-ps/networkswitchmanager/Disable-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/Enable-NetworkSwitchEthernetPort.md
  docset/winserver2022-ps/networkswitchmanager/Enable-NetworkSwitchFeature.md
  docset/winserver2022-ps/networkswitchmanager/Enable-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/Get-NetworkSwitchEthernetPort.md
  docset/winserver2022-ps/networkswitchmanager/Get-NetworkSwitchFeature.md
  docset/winserver2022-ps/networkswitchmanager/Get-NetworkSwitchGlobalData.md
  docset/winserver2022-ps/networkswitchmanager/Get-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/New-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/Remove-NetworkSwitchEthernetPortIPAddress.md
  docset/winserver2022-ps/networkswitchmanager/Remove-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/Restore-NetworkSwitchConfiguration.md
  docset/winserver2022-ps/networkswitchmanager/Save-NetworkSwitchConfiguration.md
  docset/winserver2022-ps/networkswitchmanager/Set-NetworkSwitchEthernetPortIPAddress.md
  docset/winserver2022-ps/networkswitchmanager/Set-NetworkSwitchPortMode.md
  docset/winserver2022-ps/networkswitchmanager/Set-NetworkSwitchPortProperty.md
  docset/winserver2022-ps/networkswitchmanager/Set-NetworkSwitchVlanProperty.md
Labels: Microsoft submitter

#2697 Publish 09/30/21, 3:30 PM
  docset/winserver2022-ps/iscsitarget/Export-IscsiTargetServerConfiguration.md
  docset/winserver2022-ps/iscsitarget/Import-IscsiTargetServerConfiguration.md
  docset/winserver2022-ps/netqos/Get-NetQosPolicy.md
  docset/winserver2022-ps/netqos/New-NetQosPolicy.md
  docset/winserver2022-ps/netqos/Remove-NetQosPolicy.md
  docset/winserver2022-ps/netqos/Set-NetQosPolicy.md
  docset/winserver2022-ps/networkswitchmanager/Disable-NetworkSwitchEthernetPort.md
  docset/winserver2022-ps/networkswitchmanager/Disable-NetworkSwitchFeature.md
  docset/winserver2022-ps/networkswitchmanager/Disable-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/Enable-NetworkSwitchEthernetPort.md
  docset/winserver2022-ps/networkswitchmanager/Enable-NetworkSwitchFeature.md
  docset/winserver2022-ps/networkswitchmanager/Enable-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/Get-NetworkSwitchEthernetPort.md
  docset/winserver2022-ps/networkswitchmanager/Get-NetworkSwitchFeature.md
  docset/winserver2022-ps/networkswitchmanager/Get-NetworkSwitchGlobalData.md
  docset/winserver2022-ps/networkswitchmanager/Get-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/New-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/Remove-NetworkSwitchEthernetPortIPAddress.md
  docset/winserver2022-ps/networkswitchmanager/Remove-NetworkSwitchVlan.md
  docset/winserver2022-ps/networkswitchmanager/Restore-NetworkSwitchConfiguration.md
  docset/winserver2022-ps/networkswitchmanager/Save-NetworkSwitchConfiguration.md
  docset/winserver2022-ps/networkswitchmanager/Set-NetworkSwitchEthernetPortIPAddress.md
  docset/winserver2022-ps/networkswitchmanager/Set-NetworkSwitchPortMode.md
  docset/winserver2022-ps/networkswitchmanager/Set-NetworkSwitchPortProperty.md
  docset/winserver2022-ps/networkswitchmanager/Set-NetworkSwitchVlanProperty.md
Labels: Microsoft submitter
