Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2021-01, with the labels that each got.

#2254 Resolves #2235
  docset/windows/adfs/Get-AdfsClaimDescription.md
  docset/winserver2012-ps/adfs/Get-ADFSClaimDescription.md
  docset/winserver2012r2-ps/adfs/Get-AdfsClaimDescription.md
Labels: In review, Sign off

#2255 Resolves #2243
  docset/windows/troubleshootingpack/Get-TroubleshootingPack.md
  docset/winserver2012-ps/troubleshootingpack/Get-TroubleshootingPack.md
  docset/winserver2012r2-ps/troubleshootingpack/Get-TroubleshootingPack.md
Labels: In review, Sign off

#2261 Resolves #2250
  docset/windows/addsdeployment/Install-ADDSDomainController.md
  docset/winserver2012-ps/addsdeployment/Install-ADDSDomainController.md
  docset/winserver2012r2-ps/addsdeployment/Install-ADDSDomainController.md
Labels: In review, Sign off

#2256 Resolves #2242
  docset/windows/troubleshootingpack/Invoke-TroubleshootingPack.md
  docset/winserver2012-ps/troubleshootingpack/Invoke-TroubleshootingPack.md
  docset/winserver2012r2-ps/troubleshootingpack/Invoke-TroubleshootingPack.md
Labels: In review, Sign off

#2177 add documentation for copy-settings cmdlet
  docset/windows/international/Copy-UserInternationalSettingsToSystem.md
  docset/windows/international/International.md
Labels: In review, Sign off

#2262 Resolves #2239
  docset/windows/dfsr/Get-DfsrBacklog.md
  docset/winserver2012r2-ps/dfsr/Get-DfsrBacklog.md
Labels: In review, Sign off

#2266 Publish 1/7/2021 10:30 AM PT
  docset/windows/addsdeployment/Install-ADDSDomainController.md
  docset/windows/adfs/Get-AdfsClaimDescription.md
  docset/windows/dfsr/Get-DfsrBacklog.md
  docset/windows/international/Copy-UserInternationalSettingsToSystem.md
  docset/windows/international/International.md
  docset/windows/troubleshootingpack/Get-TroubleshootingPack.md
  docset/windows/troubleshootingpack/Invoke-TroubleshootingPack.md
  docset/winserver2012-ps/addsdeployment/Install-ADDSDomainController.md
  docset/winserver2012-ps/adfs/Get-ADFSClaimDescription.md
  docset/winserver2012-ps/troubleshootingpack/Get-TroubleshootingPack.md
  docset/winserver2012-ps/troubleshootingpack/Invoke-TroubleshootingPack.md
  docset/winserver2012r2-ps/addsdeployment/Install-ADDSDomainController.md
  docset/winserver2012r2-ps/adfs/Get-AdfsClaimDescription.md
  docset/winserver2012r2-ps/dfsr/Get-DfsrBacklog.md
  docset/winserver2012r2-ps/troubleshootingpack/Get-TroubleshootingPack.md
  docset/winserver2012r2-ps/troubleshootingpack/Invoke-TroubleshootingPack.md
Labels: Microsoft submitter

#2228 Update Remove-ADGroupMember.md
  docset/windows/addsadministration/Remove-ADGroupMember.md
Labels: In review, Sign off

#2264 Resolves #2245
  docset/windows/fileserverresourcemanager/New-FsrmFileScreen.md
  docset/winserver2012-ps/fileserverresourcemanager/New-FsrmFileScreen.md
  docset/winserver2012r2-ps/fileserverresourcemanager/New-FsrmFileScreen.md
Labels: In review, Sign off

#2229 Update Add-ADGroupMember.md
  docset/windows/addsadministration/Add-ADGroupMember.md
Labels: In review, Sign off

#2257 Improves New-StoragePool
  docset/windows/storage/New-StoragePool.md
Labels: In review, Sign off

#2258 New-VirtualDisk: Corrects IsEnclosureAware's default value
  docset/windows/storage/New-VirtualDisk.md
Labels: In review, Sign off

#2269 Publish 1/13/2020, 10:30 AM PT
  docset/windows/addsadministration/Add-ADGroupMember.md
  docset/windows/addsadministration/Remove-ADGroupMember.md
  docset/windows/fileserverresourcemanager/New-FsrmFileScreen.md
  docset/windows/storage/New-StoragePool.md
  docset/windows/storage/New-VirtualDisk.md
  docset/winserver2012-ps/fileserverresourcemanager/New-FsrmFileScreen.md
  docset/winserver2012r2-ps/fileserverresourcemanager/New-FsrmFileScreen.md
Labels: Microsoft submitter

#2263 Resolves #2240
  docset/windows/bitlocker/Remove-BitLockerKeyProtector.md
  docset/winserver2012-ps/bitlocker/Remove-BitLockerKeyProtector.md
  docset/winserver2012r2-ps/bitlocker/Remove-BitLockerKeyProtector.md
Labels: In review, Sign off

#2279 Publish 1/29/2021 10:30 AM PT
  docset/windows/bitlocker/Remove-BitLockerKeyProtector.md
  docset/winserver2012-ps/bitlocker/Remove-BitLockerKeyProtector.md
  docset/winserver2012r2-ps/bitlocker/Remove-BitLockerKeyProtector.md
Labels: Microsoft submitter

#2280 Resolves #2259
  docset/windows/addsadministration/Get-ADServiceAccount.md
  docset/winserver2012-ps/activedirectory/Get-ADServiceAccount.md
  docset/winserver2012r2-ps/addsadministration/Get-ADServiceAccount.md
Labels: Back to submitter

#2281 Publish 01/21/2021, 3:30 PM
  docset/windows/addsadministration/Get-ADServiceAccount.md
  docset/winserver2012-ps/activedirectory/Get-ADServiceAccount.md
  docset/winserver2012r2-ps/addsadministration/Get-ADServiceAccount.md
Labels: Microsoft submitter
