Repository MicrosoftDocs/windows-powershell-docs, pull requests merged in 2022-05, with the labels that each got.

#2952 Correct examples to use -featureID
  docset/winserver2012r2-ps/servermigration/Import-SmigServerSetting.md
Labels: Microsoft submitter

#2960 Publish 05/06/2022, 10:30 AM
  docset/winserver2012r2-ps/servermigration/Import-SmigServerSetting.md
Labels: Microsoft submitter

#2928 Updating Get/Remove-AppSharedPacakgeContainer help
  docset/winserver2022-ps/appx/Get-AppSharedPackageContainer.md
  docset/winserver2022-ps/appx/Remove-AppSharedPackageContainer.md
Labels: Back to submitter, Microsoft submitter

#2965 Publish 05/09/2022 3:30 PM PT
  docset/winserver2022-ps/appx/Get-AppSharedPackageContainer.md
  docset/winserver2022-ps/appx/Remove-AppSharedPackageContainer.md
Labels: Microsoft submitter

#2973 [BrokenLinksH2] add 2022 versions of redirects reported as not working
  .openpublishing.redirection.json
Labels: Sign off, In review, Microsoft submitter, Admin review

#2977 29447660 - Add cmdlet multiple packaged app warning
  docset/winserver2022-ps/configci/New-CIPolicyRule.md
Labels: Microsoft submitter

#2978 pushing updates live
  docset/winserver2022-ps/configci/New-CIPolicyRule.md
Labels: Microsoft submitter

#2981 [BrokenLinksH2]
  docset/docs-conceptual/mdop/get-started.md
  docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/Microsoft.Medv.Administration.Commands.WorkspacePackager.md
  docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/export-medvworkspace.md
  docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/new-medvworkspace.md
  docset/mdop/medv/export-medvconfiguration.md
  docset/mdop/medv/medv.md
  docset/mdop/medv/new-medvconfiguration.md
Labels: Microsoft submitter

#2983 Publish 05/26/2022, 10:30 AM
  docset/docs-conceptual/mdop/get-started.md
  docset/docs-conceptual/winserver2012-ps/get-started.md
  docset/docs-conceptual/winserver2012r2-ps/get-started.md
  docset/docs-conceptual/winserver2016-ps/get-started.md
  docset/docs-conceptual/winserver2019-ps/get-started.md
  docset/docs-conceptual/winserver2022-ps/get-started.md
  docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/Microsoft.Medv.Administration.Commands.WorkspacePackager.md
  docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/export-medvworkspace.md
  docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/new-medvworkspace.md
  docset/mdop/medv/export-medvconfiguration.md
  docset/mdop/medv/medv.md
  docset/mdop/medv/new-medvconfiguration.md
Labels: Microsoft submitter

#2986 merge main to live Tues morning 10:30
  docset/winserver2012-ps/nfs/New-NfsClientgroup.md
  docset/winserver2012r2-ps/activedirectory/Search-ADAccount.md
  docset/winserver2012r2-ps/nfs/New-NfsClientgroup.md
  docset/winserver2016-ps/activedirectory/Search-ADAccount.md
  docset/winserver2016-ps/adfs/New-AdfsAzureMfaTenantCertificate.md
  docset/winserver2016-ps/adfs/Set-AdfsAzureMfaTenant.md
  docset/winserver2016-ps/hyper-v/Restart-VM.md
  docset/winserver2016-ps/nfs/New-NfsClientgroup.md
  docset/winserver2019-ps/activedirectory/Search-ADAccount.md
  docset/winserver2019-ps/adfs/New-AdfsAzureMfaTenantCertificate.md
  docset/winserver2019-ps/adfs/Set-AdfsAzureMfaTenant.md
  docset/winserver2019-ps/hyper-v/Restart-VM.md
  docset/winserver2019-ps/nfs/New-NfsClientgroup.md
  docset/winserver2022-ps/activedirectory/Search-ADAccount.md
  docset/winserver2022-ps/adfs/New-AdfsAzureMfaTenantCertificate.md
  docset/winserver2022-ps/adfs/Set-AdfsAzureMfaTenant.md
  docset/winserver2022-ps/hyper-v/Restart-VM.md
  docset/winserver2022-ps/nfs/New-NfsClientgroup.md
Labels: Microsoft submitter
